-- EXEC.md EXEC-X (go 2026-10-09: "1 3 dan 4 - jalankan sekarang"), ERRORS_AND_SOLUTIONS.md M128: the tool contracts the code now offers.
-- export_result v2: column_labels, the title of each column in the user's language for an XLSX; the
-- backend adds a column sheet (meaning and unit from AI_column_catalog for a column of the source
-- tables) and writes the definition and lineage sheets in plain words; CSV and Parquet keep the
-- machine column names.
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN (('export_result', 'v1'))) <> 1 THEN
        RAISE EXCEPTION 'Expected the previous tool versions (''export_result'', ''v1'')';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE (tool_name = 'export_result' AND version = 'v2')) THEN
        RAISE EXCEPTION 'The M128b readable Excel files tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{"columns":"at most 60 columns get a title and a meaning; a label is cut at 80 characters; a label for a column the output does not have is ignored","design":"EXEC.md EXEC-X, ERRORS_AND_SOLUTIONS.md M128 (b)","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here"}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
    ('export_result', 'v1', 'v2', '{"additionalProperties":false,"properties":{"column_labels":{"anyOf":[{"items":{"additionalProperties":false,"properties":{"column":{"description":"The column''s name in the output.","type":"string"},"label":{"description":"Its title in the user''s language.","type":"string"}},"required":["column","label"],"type":"object"},"type":"array"},{"type":"null"}],"description":"XLSX: the title the reader sees for each column, in the user''s language; a column not named keeps its name made readable."},"evidence_id":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"A checked claim''s evidence rows."},"format":{"enum":["CSV","XLSX","PARQUET"],"type":"string"},"include_definition":{"anyOf":[{"type":"boolean"},{"type":"null"}],"description":"XLSX: a sheet with the output''s definition (default true)."},"include_lineage":{"anyOf":[{"type":"boolean"},{"type":"null"}],"description":"XLSX: a sheet with where the data came from (default true)."},"output_id":{"anyOf":[{"type":"string"},{"type":"null"}]},"ref":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"The output''s value reference."}},"required":["ref","output_id","evidence_id","format","include_definition","include_lineage","column_labels"],"type":"object"}',
     'Write an output as a file the user downloads (CSV, XLSX with definition and lineage sheets, or PARQUET), at most 20 MB. Give ref (out.o3), output_id, or evidence_id (a checked claim''s evidence rows). Returns export_id, file name, size and format only; the answer names the file, the user downloads it. For XLSX give column_labels: the title of each column in the user''s language, as the reader should see it.')
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ((tool_name = 'export_result' AND version = 'v2'))) <> 1 THEN
        RAISE EXCEPTION 'The M128b readable Excel files tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'export_result' AND version = 'v2' AND input_schema::text LIKE '%column_labels%') THEN
        RAISE EXCEPTION 'The M128b readable Excel files contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
