-- final plan phase 4 (PLAN_FINAL_2026-10-04.md): the first Tool_Catalog rows of new tools.
-- find_web_fact: one fact that is not in the market data (group membership, controlling
-- shareholder, company status) from market-web-governor POST /v1/fact (S4b, user decision K8).
-- Inactive like every market-ai-orc row; input schema and purpose from the code.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name IN ('find_web_fact')) THEN
        RAISE EXCEPTION 'The final plan phase 4 tools are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
) VALUES
    ('find_web_fact', 'QUERY', 'RETRIEVAL', 'One fact that is not in the market data, from the web in about 30 seconds: for example whether a company is state-owned, its controlling shareholder, its listing status or index membership. The backend searches, keeps only values quoted verbatim from their sources and returns CONFIRMED (two independent sites or one official), CONFLICTING (every version), PARTIAL (one site) or NOT_FOUND. Ask one subject and one attribute per call; never use it for prices, volumes or any figure the database holds.',
     '{"additionalProperties":false,"properties":{"attribute":{"description":"What to find about it, e.g. ''state-owned (BUMN) or private''.","type":"string"},"subject":{"description":"The company, ticker or entity, e.g. ''BBCA''.","type":"string"}},"required":["subject","attribute"],"type":"object"}'::jsonb,
     '{"description":"status (CONFIRMED, CONFLICTING, PARTIAL, NOT_FOUND) decided by market-web-governor from verbatim quotes, the value, each version''s quotes, URLs and domains; at most about 30 seconds; no search excerpts."}'::jsonb,
     'ORCHESTRATOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40000, 200, 40000, NULL,
     false, false, false, '{"design":"PLAN_FINAL_2026-10-04.md (Fase 4, S4b)","feature_flag":"AI_ENABLE_WEB_FACT","handler":"app/tools/web_fact.py","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here","web_fact":"one subject and one attribute per call; market-web-governor /v1/fact, 30-second deadline, Postgres-E8GM web_fact cache (30 days)"}'::jsonb, 'v1', false);

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE tool_name IN ('find_web_fact') AND version = 'v1' AND NOT is_active) <> 1 THEN
        RAISE EXCEPTION 'The final plan phase 4 tools were not registered';
    END IF;
END
$verify$;

COMMIT;
