-- Round 2026-10-03 stress test fix P31 (ROUND_PLAN_2026-10-03.md): the tool contracts the code now offers.
-- get_system_capabilities v2: each capability is derived from the effect of the tools offered in the
-- step (no list of tool names); v1 named tools that did not exist and reported no web capability
-- while find_web_fact was offered (stress test ma-qa-20261005a q7, P31).
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN (('get_system_capabilities', 'v1'))) <> 1 THEN
        RAISE EXCEPTION 'Expected the previous tool versions (''get_system_capabilities'', ''v1'')';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE (tool_name = 'get_system_capabilities' AND version = 'v2')) THEN
        RAISE EXCEPTION 'The stress test fix P31 tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{"capabilities":"derived from ToolSpec.effect of the tools offered in the step (app/tools/system.py EFFECT_CAPABILITIES)","design":"ROUND_PLAN_2026-10-03.md (stress test fix P31)","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here"}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
    ('get_system_capabilities', 'v1', 'v2', '{"additionalProperties":false,"properties":{},"required":[],"type":"object"}',
     'Return what this agent can do in this step, derived from the tools it can call: each capability (read the catalog and earlier results, act on its own results, fetch market data from the database, look up one public fact on the web, run Python analysis) with the tools that provide it, the capabilities with no tool in this step, and the available tools.')
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ((tool_name = 'get_system_capabilities' AND version = 'v2'))) <> 1 THEN
        RAISE EXCEPTION 'The stress test fix P31 tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'get_system_capabilities' AND version = 'v2' AND purpose::text LIKE '%derived from the tools it can call%') THEN
        RAISE EXCEPTION 'The stress test fix P31 contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
