-- Round 2026-10-03 plan 2026-10-05 items 10 and 12 (ROUND_PLAN_2026-10-03.md): the tool contracts the code now offers.
-- check_references v1: value references rendered before the answer is written (10.2; golden test
-- ma-qa-20261005b h_add rewrote a 15,000-token answer for one address composed from memory).
-- research_web v1: facts, numbers, events, series and lists from market-web-governor POST
-- /v1/orc/web in a citable envelope (item 12; bakrie_bank ran 34 single facts, q7 read a series as
-- a conflict). lookup_reference v2, get_system_capabilities v3: descriptions name the web without
-- the one-fact tool.
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN (('lookup_reference', 'v1'), ('get_system_capabilities', 'v2'))) <> 2 THEN
        RAISE EXCEPTION 'Expected the previous tool versions (''lookup_reference'', ''v1''), (''get_system_capabilities'', ''v2'')';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE (tool_name = 'lookup_reference' AND version = 'v2') OR (tool_name = 'get_system_capabilities' AND version = 'v3')) OR EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name IN ('check_references', 'research_web')) THEN
        RAISE EXCEPTION 'The plan 2026-10-05 items 10 and 12 tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{"check_references":"at most 40 references per call; this run''s references only","design":"ROUND_PLAN_2026-10-03.md (plan 2026-10-05 items 10 and 12)","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here","web_research":"need 3-500 characters, at most 30 subjects; the web governor bounds calls and cost per user turn (WEB_ORC_MAX_CALLS_PER_RUN, WEB_ORC_MAX_USD_PER_RUN); the orchestrator waits at most 150 s and keeps 15 s of the run for the answer"}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
    ('lookup_reference', 'v1', 'v2', '{"additionalProperties":false,"properties":{"columns":{"description":"Columns to return (the entity column is always added); empty when listing.","items":{"type":"string"},"type":"array"},"match":{"anyOf":[{"additionalProperties":false,"properties":{"column":{"description":"The text column to search.","type":"string"},"text":{"description":"A case-insensitive part of its text.","type":"string"}},"required":["column","text"],"type":"object"},{"type":"null"}],"description":"A text search on one column, or null."},"table":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"A reference table, or null to list them."},"where":{"description":"Exact-value conditions, all of them must hold.","items":{"additionalProperties":false,"properties":{"column":{"description":"A column of the table, exactly as listed.","type":"string"},"values":{"description":"Exact stored values; one value, or several for any of them.","items":{"type":"string"},"type":"array"}},"required":["column","values"],"type":"object"},"type":"array"}},"required":["table","columns","where","match"],"type":"object"}',
     'Read the database''s reference tables (static classifications and profiles: a stock''s sector, industry, board, company name or description; a broker''s name or type). Without table: the tables and their columns with descriptions. With table: up to 100 rows, filtered by where (exact stored values; one value or several) and optionally by match (a case-insensitive part of one column''s text, e.g. a group or company name). Use it before a web lookup for any attribute these tables hold; the web is only for what they do not hold. Rows are current values, not as of past dates; dated data (prices, volumes, flows) needs a data need.'),
    ('get_system_capabilities', 'v2', 'v3', '{"additionalProperties":false,"properties":{},"required":[],"type":"object"}',
     'Return what this agent can do in this step, derived from the tools it can call: each capability (read the catalog and earlier results, act on its own results, fetch market data from the database, look up public information on the web, run Python analysis) with the tools that provide it, the capabilities with no tool in this step, and the available tools.')
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
) VALUES
    ('check_references', 'QUERY', 'RETRIEVAL', 'Shows what value references render to before you write the answer: give the addresses (with or without {{ }} and a format) and get each one''s displayed value, or why it does not resolve and the addresses that exist. Reads only this run''s results; no data is fetched or computed.',
     '{"additionalProperties":false,"properties":{"references":{"description":"Value references, for example ''finding.a.estimates.primary.estimate|pp:2''.","items":{"type":"string"},"type":"array"}},"required":["references"],"type":"object"}'::jsonb,
     '{"description":"per value reference: what the answer would show, or why it does not resolve with the addresses that exist (and the address it was read from when redirected); no model call, no data read."}'::jsonb,
     'ORCHESTRATOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40000, 200, 40000, NULL,
     false, false, false, '{"check_references":"at most 40 references per call; this run''s references only","design":"PLAN_2026-10-05.md items 10 and 12; ERRORS_AND_SOLUTIONS.md P35, P36, M83","feature_flag":"AI_ENABLE_ADDRESS_MENU","handler":"app/tools/references.py","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here","web_research":"need 3-500 characters, at most 30 subjects; the web governor bounds calls and cost per user turn (WEB_ORC_MAX_CALLS_PER_RUN, WEB_ORC_MAX_USD_PER_RUN); the orchestrator waits at most 150 s and keeps 15 s of the run for the answer"}'::jsonb, 'v1', false),
    ('research_web', 'QUERY', 'RETRIEVAL', 'Information that is not in the market database, from the web, for context or when the database lacks it: a fact, a figure, an event with its dates, a series over periods (for example yearly exports) or a list (for example the banks a group controls). Give one need in words, its purpose (CITE a value in the answer, CONTEXT for an analysis) and the expected shape when you know it; the same need about several companies is one call with them as subjects. The web governor searches, keeps only items quoted verbatim from their sources, labels false conflicts (different periods, definitions, units or releases) and, for a real conflict, the version it prefers (chosen_by_ai) with every version kept. Never use it for prices, volumes, flows or any figure the database holds; a web number describes and is never an input of a calculation, while an event date may set an analysis period. A run has a limited web budget: ask for what the answer needs. Each item has a ref: cite a number as {{<ref>.value_as_written}} (as its source writes it) or {{<ref>.value}} (the value at full scale, or the text of a fact or list); it is shown as a web fact with its domain. An attribute the database''s reference tables hold (sector, industry, company profile) is read with lookup_reference; this tool is refused for it until those tables have been read.',
     '{"additionalProperties":false,"properties":{"expected_shape":{"anyOf":[{"enum":["FACT","NUMBER","EVENT","SERIES","LIST"],"type":"string"},{"type":"null"}],"description":"The shape the answer should have, or null when not known."},"need":{"description":"What to find, in words, e.g. ''nilai ekspor Indonesia per tahun sejak 2018''.","type":"string"},"purpose":{"description":"CITE: values to state in the answer; CONTEXT: background for an analysis of the data.","enum":["CITE","CONTEXT"],"type":"string"},"subjects":{"description":"Companies or entities the same need is asked about, one lookup each; empty for one need.","items":{"type":"string"},"type":"array"}},"required":["need","purpose","expected_shape","subjects"],"type":"object"}'::jsonb,
     '{"description":"status (OK, PARTIAL, NOT_FOUND, BUDGET_EXHAUSTED) from market-web-governor POST /v1/orc/web; citable items (fact, number, event, series, list) with their value, value as written, period, source domain and tier, verbatim quote, conflict kind and chosen_by_ai, each a value reference web.<id>; the conflicts by item id, the sources'' domains, the web budget left; no search excerpts."}'::jsonb,
     'ORCHESTRATOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40000, 200, 40000, NULL,
     false, false, false, '{"check_references":"at most 40 references per call; this run''s references only","design":"PLAN_2026-10-05.md items 10 and 12; ERRORS_AND_SOLUTIONS.md P35, P36, M83","feature_flag":"AI_ENABLE_WEB_RESEARCH","handler":"app/tools/web_research.py","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here","web_research":"need 3-500 characters, at most 30 subjects; the web governor bounds calls and cost per user turn (WEB_ORC_MAX_CALLS_PER_RUN, WEB_ORC_MAX_USD_PER_RUN); the orchestrator waits at most 150 s and keeps 15 s of the run for the answer"}'::jsonb, 'v1', false);

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ((tool_name = 'lookup_reference' AND version = 'v2') OR (tool_name = 'get_system_capabilities' AND version = 'v3'))) <> 2
       OR (SELECT count(*) FROM public."Tool_Catalog" WHERE tool_name IN ('check_references', 'research_web') AND version = 'v1' AND NOT is_active) <> 2 THEN
        RAISE EXCEPTION 'The plan 2026-10-05 items 10 and 12 tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'lookup_reference' AND version = 'v2' AND purpose::text LIKE '%before a web lookup%')
       OR NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'get_system_capabilities' AND version = 'v3' AND purpose::text LIKE '%look up public information on the web%') THEN
        RAISE EXCEPTION 'The plan 2026-10-05 items 10 and 12 contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
