-- Multi-Angle Research: the research library (C07; MULTI_ANGLE_FIX_PLAN.md item 2, user decision 2026-09-29).
-- public."AI_research_library" is the model-facing description of the eight methods the sandbox engines compute;
-- market-ai-orc serves it (get_research_library) instead of listing methods in its system prompt. It describes, it
-- does not compute: a new row does not create a method. AI_research_catalog is not touched.
-- GENERATED by scripts/generate_ai_research_library_migration.py from apps/market-python-sandbox/app/research_library.py
-- (library_sha256 b4f10f55fd1ad4919be0eeca74b64dae955d46148fa027ec4a70ed9a01e17058); the sandbox test tests/test_research_library.py fails on drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF to_regclass('public."AI_research_library"') IS NOT NULL THEN
        RAISE EXCEPTION 'AI_research_library already exists';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_ai_catalog_reader') THEN
        RAISE EXCEPTION 'market_ai_catalog_reader role is required';
    END IF;
END
$preflight$;

CREATE TABLE public."AI_research_library" (
    method_id text NOT NULL,
    engine_version integer NOT NULL,
    library_version integer NOT NULL,
    method_family text NOT NULL,
    question_shape text NOT NULL,
    input_roles jsonb NOT NULL,
    required_parameters jsonb NOT NULL,
    optional_parameters jsonb NOT NULL,
    data_requirements jsonb NOT NULL,
    common_requirements jsonb NOT NULL,
    sample_unit text NOT NULL,
    secondary_checks jsonb NOT NULL,
    decision_rules_ref text NOT NULL,
    interpretation text NOT NULL,
    misuse_warning text NOT NULL,
    example_question text NOT NULL,
    library_sha256 text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AI_research_library_pkey" PRIMARY KEY (method_id, engine_version),
    CONSTRAINT ai_research_library_family CHECK (method_family IN ('CONDITIONAL_OUTCOME', 'PERSISTENCE',
        'GROUP_COMPARISON', 'QUANTILE_RANKING', 'TEMPORAL_DEPENDENCY')),
    CONSTRAINT ai_research_library_sample_unit CHECK (sample_unit IN ('DATES', 'ENTITIES',
        'DATES_AUTOCORRELATION_ADJUSTED')),
    CONSTRAINT ai_research_library_sha CHECK (library_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ai_research_library_json CHECK (
        jsonb_typeof(input_roles) = 'array' AND jsonb_typeof(required_parameters) = 'array'
        AND jsonb_typeof(optional_parameters) = 'array' AND jsonb_typeof(data_requirements) = 'object'
        AND jsonb_typeof(common_requirements) = 'array' AND jsonb_typeof(secondary_checks) = 'array'),
    CONSTRAINT ai_research_library_method_id CHECK (method_id ~ '^[a-z][a-z0-9_]{0,62}$')
);
COMMENT ON TABLE public."AI_research_library" IS
    'Model-facing description of the Multi-Angle Research methods the sandbox engines compute; generated from code, '
    'hash-bound (library_sha256). Enforcement stays in code.';

-- market-ai-orc's catalog login inherits this role; the SQL Governor role gets no grant.
GRANT SELECT ON public."AI_research_library" TO market_ai_catalog_reader;
REVOKE ALL ON public."AI_research_library" FROM PUBLIC;

INSERT INTO public."AI_research_library" (
    method_id, engine_version, library_version, method_family, question_shape, input_roles, required_parameters,
    optional_parameters, data_requirements, common_requirements, sample_unit, secondary_checks, decision_rules_ref,
    interpretation, misuse_warning, example_question, library_sha256
)
SELECT r.method_id, r.engine_version, r.library_version, r.method_family, r.question_shape, r.input_roles,
       r.required_parameters, r.optional_parameters, r.data_requirements, r.common_requirements, r.sample_unit,
       r.secondary_checks, r.decision_rules_ref, r.interpretation, r.misuse_warning, r.example_question,
       'b4f10f55fd1ad4919be0eeca74b64dae955d46148fa027ec4a70ed9a01e17058'
FROM jsonb_to_recordset($library$[
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "REQUIRED",
   "label": "CONSTANT_PER_ENTITY",
   "min_entities_per_date": null,
   "notes": [
    "An entity that changes label is refused (COHORT_NOT_CONSTANT).",
    "Each entity's mean outcome is one observation: the sample is the number of entities."
   ],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "After a 60-day drawdown above 30%, is the 20-day return different for energy, basic materials and financial stocks?",
  "input_roles": [
   {
    "meaning": "The cohort label; one label per entity for the whole input.",
    "required": true,
    "role": "group",
    "type": "LABEL"
   },
   {
    "meaning": "The measured result, normally {'forward_return': '<price column>'} over the approved horizon.",
    "required": true,
    "role": "outcome",
    "type": "NUMBER"
   }
  ],
  "interpretation": "Differences of the per-entity mean outcome between cohorts (Welch), corrected for the comparisons.",
  "library_version": 1,
  "method_family": "GROUP_COMPARISON",
  "method_id": "cohort_comparison",
  "misuse_warning": "Few entities per cohort give a weak test; current-state labels (sector) are applied to the whole history.",
  "optional_parameters": [],
  "question_shape": "Is the outcome different between groups of entities (a fixed label per entity)?",
  "required_parameters": [
   {
    "name": "groups",
    "rule": "2 to 12 short labels (at most 60 characters), in the order the hypothesis reads."
   },
   {
    "name": "comparison",
    "rule": "PAIRWISE, VS_REST or FIRST_VS_OTHERS; the implied pairwise comparisons must be declared in pairwise_comparisons."
   }
  ],
  "sample_unit": "ENTITIES",
  "secondary_checks": []
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "OPTIONAL",
   "label": null,
   "min_entities_per_date": null,
   "notes": [],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "Do bank stocks that fall more than 5% in a day return more over the next 5 days than on other days?",
  "input_roles": [
   {
    "meaning": "True on the rows where the condition holds (past values only).",
    "required": true,
    "role": "condition",
    "type": "BOOLEAN"
   },
   {
    "meaning": "The measured result, normally {'forward_return': '<price column>'} over the approved horizon.",
    "required": true,
    "role": "outcome",
    "type": "NUMBER"
   }
  ],
  "interpretation": "The mean outcome after the condition minus the baseline mean, with a 95% interval from the spread of per-date means, and the difference in the share of positive outcomes.",
  "library_version": 1,
  "method_family": "CONDITIONAL_OUTCOME",
  "method_id": "conditional_distribution",
  "misuse_warning": "A historical association only, not a cause or a prediction; a rare condition gives an anecdotal sample.",
  "optional_parameters": [],
  "question_shape": "After a condition holds, is the outcome different from the baseline?",
  "required_parameters": [
   {
    "name": "baseline_mode",
    "rule": "COMPLEMENT (rows without the condition) or ALL (every row)."
   }
  ],
  "sample_unit": "DATES",
  "secondary_checks": []
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "OPTIONAL",
   "label": null,
   "min_entities_per_date": null,
   "notes": [
    "A panel is reduced to per-date means; a date's condition holds only when it holds for every entity that date."
   ],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "How strong is the link between the change in 20-day volatility and the next 20-day return of healthcare stocks?",
  "input_roles": [
   {
    "meaning": "The first series.",
    "required": true,
    "role": "leader",
    "type": "NUMBER"
   },
   {
    "meaning": "The second series, normally a forward return.",
    "required": true,
    "role": "follower",
    "type": "NUMBER"
   },
   {
    "meaning": "Optional: the relation when it holds against when it does not.",
    "required": false,
    "role": "condition",
    "type": "BOOLEAN"
   }
  ],
  "interpretation": "The correlation at the lag, a rolling correlation and, with a condition, the difference between the two conditional correlations.",
  "library_version": 1,
  "method_family": "TEMPORAL_DEPENDENCY",
  "method_id": "correlation_dependency",
  "misuse_warning": "Averaging a panel into one series hides differences between entities.",
  "optional_parameters": [
   {
    "name": "primary_lag",
    "rule": "An integer from 0 to 260 (default 0)."
   },
   {
    "name": "rolling_window",
    "rule": "An integer from 5 to 260 for a rolling correlation."
   }
  ],
  "question_shape": "How strong is the relation between two series, is it stable, and does it change under a condition?",
  "required_parameters": [
   {
    "name": "correlation_method",
    "rule": "PEARSON or SPEARMAN."
   }
  ],
  "sample_unit": "DATES_AUTOCORRELATION_ADJUSTED",
  "secondary_checks": []
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "OPTIONAL",
   "label": null,
   "min_entities_per_date": null,
   "notes": [
    "A panel is reduced to per-date means (one series).",
    "Needs more dates than the largest lag."
   ],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "Does daily foreign net buying of large banks lead their returns 1 to 5 days later?",
  "input_roles": [
   {
    "meaning": "The earlier series.",
    "required": true,
    "role": "leader",
    "type": "NUMBER"
   },
   {
    "meaning": "The later series, normally a forward return.",
    "required": true,
    "role": "follower",
    "type": "NUMBER"
   }
  ],
  "interpretation": "The correlation at every lag (the lag curve), the predeclared lag as primary, with an effective sample reduced for autocorrelation.",
  "library_version": 1,
  "method_family": "TEMPORAL_DEPENDENCY",
  "method_id": "lead_lag",
  "misuse_warning": "A correlation is not a cause; several lags need a multiple-testing policy.",
  "optional_parameters": [],
  "question_shape": "Is the leader today correlated with the follower k observations later?",
  "required_parameters": [
   {
    "name": "lags",
    "rule": "1 to 20 distinct integers from 0 to 260."
   },
   {
    "name": "primary_lag",
    "rule": "One of lags: the predeclared lag reported as primary."
   },
   {
    "name": "correlation_method",
    "rule": "PEARSON or SPEARMAN."
   }
  ],
  "sample_unit": "DATES_AUTOCORRELATION_ADJUSTED",
  "secondary_checks": []
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "REQUIRED",
   "label": null,
   "min_entities_per_date": "buckets",
   "notes": [
    "Dates with fewer entities than buckets are skipped."
   ],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "Do industrial stocks in the highest volume-ratio quintile return more over 10 days than the lowest?",
  "input_roles": [
   {
    "meaning": "The value that ranks the entities on each date.",
    "required": true,
    "role": "signal",
    "type": "NUMBER"
   },
   {
    "meaning": "The measured result, normally {'forward_return': '<price column>'} over the approved horizon.",
    "required": true,
    "role": "outcome",
    "type": "NUMBER"
   }
  ],
  "interpretation": "The mean top-minus-bottom spread per date, the monotonicity of the bucket means (must pass for SUPPORTED) and the mean rank correlation (IC).",
  "library_version": 1,
  "method_family": "QUANTILE_RANKING",
  "method_id": "quantile_ranking",
  "misuse_warning": "Needs a cross-section: one or two stocks cannot be ranked.",
  "optional_parameters": [],
  "question_shape": "On the same date, do entities with a higher signal have a higher outcome?",
  "required_parameters": [
   {
    "name": "buckets",
    "rule": "An integer from 2 to 10 (equal-count groups per date)."
   }
  ],
  "sample_unit": "DATES",
  "secondary_checks": [
   "monotonicity"
  ]
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "OPTIONAL",
   "label": "CONSTANT_PER_DATE",
   "min_entities_per_date": null,
   "notes": [
    "A label that differs between stocks on the same date is not a regime (REGIME_NOT_CONSTANT); use cohort_comparison or quantile_ranking for it.",
    "Only the approved labels may appear (UNDECLARED_GROUP)."
   ],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "Is the 10-day return different when the market is above or below its 26-day average?",
  "input_roles": [
   {
    "meaning": "The regime label; the same for every entity on a date.",
    "required": true,
    "role": "group",
    "type": "LABEL"
   },
   {
    "meaning": "The measured result, normally {'forward_return': '<price column>'} over the approved horizon.",
    "required": true,
    "role": "outcome",
    "type": "NUMBER"
   }
  ],
  "interpretation": "Differences of the per-date mean outcome between regimes, corrected for the comparisons.",
  "library_version": 1,
  "method_family": "GROUP_COMPARISON",
  "method_id": "regime_comparison",
  "misuse_warning": "Regimes chosen after looking at the data, or years used as regimes, describe history only.",
  "optional_parameters": [],
  "question_shape": "Is the outcome different between market regimes (a label of the date)?",
  "required_parameters": [
   {
    "name": "groups",
    "rule": "2 to 12 short labels (at most 60 characters), in the order the hypothesis reads."
   },
   {
    "name": "comparison",
    "rule": "PAIRWISE, VS_REST or FIRST_VS_OTHERS; the implied pairwise comparisons must be declared in pairwise_comparisons."
   }
  ],
  "sample_unit": "DATES",
  "secondary_checks": []
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "OPTIONAL",
   "label": null,
   "min_entities_per_date": null,
   "notes": [
    "The outcome is whether the state stays true over the next horizon observations; no return is measured. For the return after a streak use conditional_distribution with the streak as its condition.",
    "Needs consecutive observations per entity."
   ],
   "outcome": "STATE_CONTINUATION"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "After three up days in a row, how often does the next day rise too?",
  "input_roles": [
   {
    "meaning": "True while the state holds, per entity in date order.",
    "required": true,
    "role": "state",
    "type": "BOOLEAN"
   }
  ],
  "interpretation": "The continuation rate after streaks of at least k against the base rate of continuation, with the distribution of streak lengths.",
  "library_version": 1,
  "method_family": "PERSISTENCE",
  "method_id": "streak_persistence",
  "misuse_warning": "Says nothing about returns; overlapping streaks of the same entity are not independent.",
  "optional_parameters": [],
  "question_shape": "After a state has held for k observations in a row, how often does it continue?",
  "required_parameters": [
   {
    "name": "streak_lengths",
    "rule": "1 to 10 distinct integers from 1 to 20."
   }
  ],
  "sample_unit": "DATES",
  "secondary_checks": []
 },
 {
  "common_requirements": [
   "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
   "Declarative form: every role is an expression over the columns of one data request of the angle's contract; a forward return may name another contract request that holds the price column.",
   "A forward-return outcome needs a numeric price-level column and a future buffer of at least the horizon; rows without a later value are censored.",
   "A return outcome (PERCENT or DECIMAL) is never a price level or a trailing return column (OUTCOME_NOT_APPROVED).",
   "The effective sample counts dates at least one horizon apart, so overlapping outcomes are not counted twice."
  ],
  "data_requirements": {
   "entity_column": "OPTIONAL",
   "label": null,
   "min_entities_per_date": null,
   "notes": [
    "Every threshold is one comparison: more than one needs a multiple-testing policy other than NONE."
   ],
   "outcome": "FORWARD_RETURN"
  },
  "decision_rules_ref": "research_engines.decide v1: MULTI_ANGLE_RESEARCH.md section 4",
  "engine_version": 1,
  "example_question": "Is the 5-day rebound after a daily fall different for falls of 3%, 5%, 7% and 10%?",
  "input_roles": [
   {
    "meaning": "The value compared with each approved threshold.",
    "required": true,
    "role": "signal",
    "type": "NUMBER"
   },
   {
    "meaning": "The measured result, normally {'forward_return': '<price column>'} over the approved horizon.",
    "required": true,
    "role": "outcome",
    "type": "NUMBER"
   }
  ],
  "interpretation": "The difference from the baseline at every threshold, corrected for multiple testing; the reported candidate is the most significant one in the expected direction.",
  "library_version": 1,
  "method_family": "CONDITIONAL_OUTCOME",
  "method_id": "threshold_sensitivity",
  "misuse_warning": "Trying many thresholds and keeping the best one overstates the effect; read the corrected interval.",
  "optional_parameters": [],
  "question_shape": "Does the effect depend on how large the signal is (several thresholds)?",
  "required_parameters": [
   {
    "name": "thresholds",
    "rule": "1 to 20 distinct numbers in the signal's own unit."
   },
   {
    "name": "threshold_operator",
    "rule": ">= or <=, applied as signal operator threshold."
   },
   {
    "name": "baseline_mode",
    "rule": "COMPLEMENT (rows without the condition) or ALL (every row)."
   }
  ],
  "sample_unit": "DATES",
  "secondary_checks": []
 }
]$library$::jsonb) AS r(
    method_id text, engine_version integer, library_version integer, method_family text, question_shape text,
    input_roles jsonb, required_parameters jsonb, optional_parameters jsonb, data_requirements jsonb,
    common_requirements jsonb, sample_unit text, secondary_checks jsonb, decision_rules_ref text,
    interpretation text, misuse_warning text, example_question text);

INSERT INTO public."Table_Catalog" (
    table_schema, table_name, category, definition, grain,
    primary_key_columns, source_system, source_tables, source_code_paths,
    update_rule, related_functions, documentation_status,
    readiness_mode, readiness_date_column, observation_date_column,
    data_available_at_column, availability_rule, point_in_time_status,
    historical_metadata_method
) VALUES (
    'public', 'AI_research_library', 'Reference',
    'Model-facing description of the eight Multi-Angle Research methods (roles, parameters, data requirements, '
    'interpretation, misuse warning), generated from the sandbox research library and bound to it by library_sha256.',
    'One row per research method and engine version', ARRAY['method_id', 'engine_version'],
    'apps/market-python-sandbox/app/research_library.py (byte-identical in market-ai-orc)',
    ARRAY[]::text[], ARRAY['database/migrations/20260930_001_create_ai_research_library.sql',
                          'apps/market-python-sandbox/app/research_library.py',
                          'scripts/generate_ai_research_library_migration.py'],
    'Regenerated by a forward migration whenever the library in code changes; never edited by hand.',
    ARRAY[]::text[], 'VERIFIED', 'NOT_APPLICABLE', NULL, NULL, NULL,
    'Metadata only; enforcement is the engines and the feasibility check in code.',
    'NOT_APPLICABLE', NULL
);

INSERT INTO public."Column_Catalog" (
    table_schema, table_name, column_name, ordinal_position, data_type,
    is_nullable, default_expression, is_primary_key, definition,
    source_column_or_expression, unit, null_rule, source_code_paths,
    documentation_status
)
SELECT columns.table_schema, columns.table_name, columns.column_name, columns.ordinal_position,
       columns.data_type, false, columns.column_default, columns.column_name IN ('method_id', 'engine_version'),
       CASE columns.column_name
        WHEN 'method_id' THEN 'Registered method id (research_plan/v2 method_id).'
        WHEN 'engine_version' THEN 'Version of the statistical engines the row describes.'
        WHEN 'library_version' THEN 'Version of the research library content.'
        WHEN 'method_family' THEN 'One of the five method families; an agreement between angles needs two families.'
        WHEN 'question_shape' THEN 'The question the method answers, in general form.'
        WHEN 'input_roles' THEN 'JSON array of input roles (role, type, required, meaning); logical roles, not column names.'
        WHEN 'required_parameters' THEN 'JSON array of the parameters an angle of this method must set, with their rules.'
        WHEN 'optional_parameters' THEN 'JSON array of the parameters an angle may set, with their rules.'
        WHEN 'data_requirements' THEN 'JSON object: entity column, label constancy, outcome kind, minimum entities per date and notes; the feasibility check enforces them.'
        WHEN 'common_requirements' THEN 'JSON array of the requirements every method shares (one row per entity and date, declarations, forward returns).'
        WHEN 'sample_unit' THEN 'Unit of the effective sample: DATES, ENTITIES or DATES_AUTOCORRELATION_ADJUSTED.'
        WHEN 'secondary_checks' THEN 'JSON array of checks that must pass for SUPPORTED (for example monotonicity).'
        WHEN 'decision_rules_ref' THEN 'Where the status rules are defined; enforcement is research_engines.decide in code.'
        WHEN 'interpretation' THEN 'What the method''s estimate means.'
        WHEN 'misuse_warning' THEN 'How the result is commonly misread.'
        WHEN 'example_question' THEN 'An illustrative question the method answers.'
        WHEN 'library_sha256' THEN 'Hash of the whole library; market-ai-orc enables multi-angle research only when it equals the sandbox''s and its own.'
        WHEN 'is_active' THEN 'Whether the method is offered to the model.'
        WHEN 'created_at' THEN 'Row creation time.'
        WHEN 'updated_at' THEN 'Last update time.'
       END,
       'app/research_library.py (rows())', NULL, 'NULL is not permitted.',
       ARRAY['database/migrations/20260930_001_create_ai_research_library.sql'], 'VERIFIED'
FROM information_schema.columns AS columns
WHERE columns.table_schema = 'public' AND columns.table_name = 'AI_research_library';

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."AI_research_library" WHERE is_active AND library_sha256 = 'b4f10f55fd1ad4919be0eeca74b64dae955d46148fa027ec4a70ed9a01e17058') <> 8
       OR (SELECT count(DISTINCT method_family) FROM public."AI_research_library") <> 5 THEN
        RAISE EXCEPTION 'Expected 8 active research library rows with the library hash and five families';
    END IF;
    IF (SELECT count(*) FROM public."Column_Catalog" WHERE table_name = 'AI_research_library'
          AND definition IS NOT NULL) <> 20
       OR NOT EXISTS (SELECT 1 FROM public."Table_Catalog" WHERE table_name = 'AI_research_library') THEN
        RAISE EXCEPTION 'AI_research_library lacks its Table_Catalog / Column_Catalog definitions';
    END IF;
    IF NOT has_table_privilege('market_ai_catalog_reader', 'public."AI_research_library"', 'SELECT')
       OR has_table_privilege('market_ai_catalog_reader', 'public."AI_research_library"', 'INSERT,UPDATE,DELETE') THEN
        RAISE EXCEPTION 'market_ai_catalog_reader privileges do not match the read-only contract';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_ai_sql_reader')
       AND has_table_privilege('market_ai_sql_reader', 'public."AI_research_library"', 'SELECT') THEN
        RAISE EXCEPTION 'The SQL Governor unexpectedly reads the research library';
    END IF;
END
$verify$;
COMMIT;
