-- Method guides version 7 (EXEC.md EXEC-W wave B / EXEC-Y Fase 4 (M119, go 2026-10-09): a session loads the tables it
-- emitted by name, keeps working tables (save_table / load_table), and event_study and backtest name
-- every table they emitted). Adds the version 7 rows; the earlier
-- version's rows stay, so a market-ai-orc still on it keeps its guides until it is replaced (each service reads the
-- version of its own code).
-- GENERATED by scripts/generate_ai_method_guide_migration.py from apps/market-python-sandbox/app/method_guides.py
-- (guides_sha256 2863d4073a1d12aa456ced7082a5355d0a5065903f1e89abfb2f6164b74a5968); the sandbox test tests/test_method_guides.py fails on drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF to_regclass('public."AI_method_guide"') IS NULL THEN
        RAISE EXCEPTION 'AI_method_guide does not exist (migration 20261002_001)';
    END IF;
    IF EXISTS (SELECT 1 FROM public."AI_method_guide" WHERE guides_version = 7) THEN
        RAISE EXCEPTION 'Method guides version 7 are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."AI_method_guide" (name, guides_version, kind, g, guide, guide_sha256, guides_sha256)
SELECT r.name, r.guides_version, r.kind, r.g, r.guide, r.guide_sha256, '2863d4073a1d12aa456ced7082a5355d0a5065903f1e89abfb2f6164b74a5968'
FROM jsonb_to_recordset($guides$[
 {
  "g": "G1",
  "guide": {
   "avoid_when": [
    "The outcome after an event, when event_study is offered (its result is recalculated by the backend).",
    "Testing a hypothesis with a verdict: that needs a research plan the user approves."
   ],
   "common_errors": [
    {
     "code": "SanitiError: 1 is not a data request",
     "fix": "range(n) is Python's built-in; one approved range is load_range(request, range_id) or saniti.range.",
     "seen_in": "S21"
    },
    {
     "code": "MaterializationLimitExceeded",
     "fix": "aggregate in sql() (GROUP BY the entity and date columns) before loading into pandas.",
     "seen_in": "G14"
    },
    {
     "code": "TypeError on a date comparison",
     "fix": "the time column holds datetime.date objects: compare with datetime.date or convert with pd.to_datetime first.",
     "seen_in": "2026-09-26 stress test"
    },
    {
     "code": "a unit shown twice",
     "fix": "a format such as pct, pp or rp already shows its unit: do not type it after the reference.",
     "seen_in": "P22"
    },
    {
     "code": "is not a table this session can load",
     "fix": "a table emitted in the same run_python is still your variable; from the next run_python load it with load_output(name); keep any other frame with save_table(name, frame).",
     "seen_in": "M119"
    }
   ],
   "examples": [
    {
     "code": "top = sql('SELECT ticker, max(close) AS high, min(close) AS low FROM prices GROUP BY ticker ORDER BY high DESC')\nload('stock_classification')\nemit_table('high_low', top, definition={})",
     "runnable": true,
     "title": "Ranking from a SQL summary"
    },
    {
     "code": "now = load_range('prices', 'current_ytd')\nbefore = load_range('prices', 'previous_comparable')\nload('stock_classification')\nchange = (now.groupby('ticker')['close'].last() - before.groupby('ticker')['close'].last()).rename('change')\nshare = (change / change.abs().sum()).rename('share_of_total_move')\nemit_table('drivers', pd.concat([change, share], axis=1).sort_values('change'), definition={})",
     "runnable": true,
     "title": "Contribution of each entity to a change between two ranges"
    }
   ],
   "g": "G1",
   "helpers": [],
   "inputs": [
    {
     "name": "code",
     "rule": "Python for run_python. Read data only through the saniti helpers (load, load_range, sql, join, preaggregate, resample, period_return); a read outside them counts as not processed."
    }
   ],
   "insight": [
    "Start from the explained result's own table (load_output) and its definition in the data record (filters, period, thresholds); never guess how an earlier result was made, and say how a different definition differs.",
    "Answer why with a computed breakdown, not a guess: change between periods, top and bottom contributors, the measure split by a dimension, unusual values, concentration.",
    "Split only by catalog columns that are groupable; add values only where the catalog's aggregation rule is SUM.",
    "Compare with a baseline (other entities, other periods) and size the difference.",
    "Call the result an association, not a cause; causes outside the database (news, corporate actions) are not available; offer a test (event study or a research plan) when the user wants evidence."
   ],
   "kind": "PATH",
   "limits": [
    "A frame larger than the session's frame budget is refused before it loads (MaterializationLimitExceeded): reduce it in sql() first; the session and its variables stay.",
    "A table of an earlier result is loaded with load_output(output_id) (carried() lists them with their labels); a figure built on it is never better checked than its label.",
    "A table this session emitted in an earlier run_python is loaded the same way, by output_id or name (label NOT_RELEASED until complete_analysis releases it). A frame needed again later is kept with save_table(name, frame) and read with load_table(name): working tables share the session's working_table_bytes, are never released and never cited; emit_table what you cite.",
    "complete_analysis needs every approved request and range read in a successful execution and at least one output.",
    "Every released table or JSON states how it was made: emit_table(name, frame, description, definition={'filters': [{'column', 'operator', 'value'}], 'period': {'start', 'end'}, 'thresholds': {...}, 'notes': '...'}) ({} when the code applied no filter beyond the data request); complete_analysis does not release a result without one. Put row filters in the data request's scope where you can, so the backend records them itself.",
    "Only released outputs may be cited; print() is diagnostics only.",
    "A sample size or a period's observation count uses the rows inside the approved ranges (in_period(frame, request) or load_range): load() and include_buffers=True add warm-up and forward rows that feed indicators only. When warm-up rows were used, state both spans (the bundle's rows_in_ranges and rows_extracted).",
    "A z-score that finds a spike in an activity series (volume, traded value or lots, a broker or foreign flow: the catalog sums it over time) compares the observation with the ones before it: the rolling mean and deviation of x.shift(1), as Pine's ta.sma(volume[1], n); a price z-score keeps the current observation.",
    "Release every figure the answer cites (its table or JSON output), so the answer writes it by its address: a figure typed from your code without an address is refused once."
   ],
   "name": "free_code",
   "results": "Released outputs of complete_analysis, cited as value references such as {{out.o1.rows[<column>=<value>].<column>}}.",
   "title": "Free analysis code in the session",
   "use_when": [
    "A calculation, ranking, screen, description or comparison that no other method covers.",
    "Explaining a result (why, what drives it, what stands out) by computing it from the data and outputs already in the session.",
    "Exploring the data first: each dataset's profile (in the session view) shows its columns, ranges, frequent values and sample rows; print or inspect more before deciding the method."
   ],
   "verification": {
    "checked": [
     "every approved request and range was delivered and read",
     "every figure of the answer comes from a released output (value references)",
     "every cited figure is read by the backend from its released output (DIRUJUK); it is not recomputed apart from your code"
    ],
    "level": "DATA_COVERAGE_VERIFIED",
    "not_checked": [
     "the formula of your code: say that the calculation was not independently recalculated"
    ]
   }
  },
  "guide_sha256": "fe28e710aefc6f345ed6762345d3c534c3fb71202e27c6e7d71ae1d36a153703",
  "guides_version": 7,
  "kind": "PATH",
  "name": "free_code"
 },
 {
  "g": "G2",
  "guide": {
   "avoid_when": [
    "A request with more than one row per entity and date (for example per broker): reduce it to one row per entity and date first, or use another request.",
    "A verdict on a hypothesis: pass the events to a hypothesis plan."
   ],
   "common_errors": [
    {
     "code": "DUPLICATE_ENTITY_DATE",
     "fix": "use a request with one row per entity and date, or narrow its scope.",
     "seen_in": "event_study"
    },
    {
     "code": "EXPRESSION_INVALID",
     "fix": "use only the request's columns and the expression functions; the name in the message is the one that is unknown.",
     "seen_in": "event_study"
    },
    {
     "code": "CALCULATION_MISMATCH",
     "fix": "never overwrite or re-emit the study's tables; run event_study again under the same name.",
     "seen_in": "event_study"
    },
    {
     "code": "a price level as the outcome",
     "fix": "the outcome is {'forward_return': '<price column>'}; the backend computes the return.",
     "seen_in": "S15"
    }
   ],
   "examples": [
    {
     "code": "study = event_study('prices', 'close / lag(close, 1) - 1 <= -0.05', {'forward_return': 'close'}, 5, name='drops')\nload('stock_classification')\nprint(study['summary'][0]['event_count'])",
     "runnable": true,
     "title": "Five-day return after a fall of at least five percent"
    },
    {
     "code": "study = event_study('prices', 'close > rolling_mean(close, 5)', {'forward_return': 'close'}, 1, range_id='current_ytd', overlap_policy='ALL', baseline='NON_EVENT', name='above_mean')\nload('prices')\nload('stock_classification')",
     "runnable": true,
     "title": "One range, every event, compared with the days without an event"
    }
   ],
   "g": "G2",
   "helpers": [
    "event_study"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "event_study",
     "rule": "The data request id or logical name."
    },
    {
     "name": "event",
     "of": "event_study",
     "rule": "A condition, an expression over the request's columns, per entity and past values only: + - * / **, comparisons, & | ~, abs log exp sqrt sign min max where, lag(x, k), rolling_sum(x, n), rolling_mean(x, n); for example close / lag(close, 1) - 1 <= -0.05."
    },
    {
     "name": "outcome",
     "of": "event_study",
     "rule": "{'forward_return': '<price column>'}; add 'request': '<data request id>' when the price is in another request. Never a price level or a trailing return column."
    },
    {
     "name": "horizon",
     "of": "event_study",
     "rule": "Observations the outcome spans (one to two hundred sixty)."
    },
    {
     "default": null,
     "name": "range_id",
     "of": "event_study",
     "rule": "One approved range, or every range (each range is studied on its own window)."
    },
    {
     "default": "NON_OVERLAPPING",
     "name": "overlap_policy",
     "of": "event_study",
     "rule": "NON_OVERLAPPING keeps an entity's next event only a horizon after the last one it kept; ALL keeps every event."
    },
    {
     "default": "ALL_ELIGIBLE",
     "name": "baseline",
     "of": "event_study",
     "rule": "ALL_ELIGIBLE (every row with a defined condition and outcome) or NON_EVENT (the rows without the event)."
    },
    {
     "default": null,
     "name": "min_events",
     "of": "event_study",
     "rule": "The policy minimum reported as meets_min_events (default thirty); it never drops the study."
    },
    {
     "default": null,
     "name": "holdout_start",
     "of": "event_study",
     "rule": "A date YYYY-MM-DD: adds IN_SAMPLE and OUT_OF_SAMPLE rows."
    },
    {
     "default": null,
     "name": "outcome_unit",
     "of": "event_study",
     "rule": "PERCENT or DECIMAL; leave unset in a research session (the approved experiment's unit is used, a different one is refused)."
    },
    {
     "default": null,
     "name": "name",
     "of": "event_study",
     "rule": "The output name (event_study_<n> when omitted)."
    }
   ],
   "kind": "PATH",
   "limits": [
    "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
    "Ranges of the request may not overlap (RANGES_OVERLAP); choose one with range_id.",
    "An event whose outcome runs past the delivered data is censored and counted apart.",
    "The request is loaded whole, so it must fit the session's frame budget."
   ],
   "name": "event_study",
   "results": "Four tables: <name> (one row per segment ALL, IN_SAMPLE, OUT_OF_SAMPLE: event_count, event_dates, effective_event_dates, mean, median, hit_rate, baseline_count, baseline_mean, baseline_median, delta_mean, delta_ci_low, delta_ci_high, delta_p_value, censored_count, overlapping_dropped, meets_min_events), <name>_events (date, entity, outcome), <name>_baseline and <name>_flow (rows_in_window, condition_unknown, condition_true = the qualifying events, censored, overlapping_dropped, used; condition_true = censored + overlapping_dropped + used); the call also returns the events, baseline and flow frames, tables (the name of each table, which load_output(name) reads in a later run_python) and rows_in_period (the rows each range used; buffer rows only fed lags and forward returns). Cite {{out.o1.rows[segment=ALL].delta_mean}}; quote every count of the event flow from <name>_flow, never derive one. The interval and p-value treat events on one date as one observation.",
   "title": "Event study: the outcome after an event against a baseline",
   "use_when": [
    "What happened after an event (a fall, a spike, a flow above a level): the forward return after it against a baseline, with the number of events and its uncertainty.",
    "Building the events and baseline rows of a hypothesis plan."
   ],
   "verification": {
    "checked": [
     "complete_analysis rebuilds the events and outcomes from the declaration and the bundle files and recomputes both tables; a match labels them CALCULATION_VERIFIED",
     "a released table that differs fails completion (CALCULATION_MISMATCH)"
    ],
    "level": "FORMULA_AND_STATISTICS_VERIFIED",
    "not_checked": [
     "anything you compute afterwards from the tables or frames in your own code"
    ]
   }
  },
  "guide_sha256": "862c53757a8b5e087ec5a9ce9797969f046b0453bb3e8681af437ae3e4defa3b",
  "guides_version": 7,
  "kind": "PATH",
  "name": "event_study"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "The average outcome after an event against a baseline (event_study).",
    "Adding exit rules the user did not state: use only the stop, target, exit signal or holding limit the user or the script gives, and name any you assume as a choice."
   ],
   "common_errors": [
    {
     "code": "PRICE_COLUMN_MISSING",
     "fix": "pass prices={'open': ..., 'high': ..., 'low': ..., 'close': ...} with the request's columns.",
     "seen_in": "backtest"
    },
    {
     "code": "CALCULATION_MISMATCH",
     "fix": "never overwrite or re-emit the backtest's tables; run backtest again under the same name.",
     "seen_in": "backtest"
    },
    {
     "code": "warm-up bars counted as the test period",
     "fix": "quote bars_in_period; the warm-up rows are bars_buffer.",
     "seen_in": "P32"
    }
   ],
   "examples": [
    {
     "code": "full = load('prices').sort_values(['ticker', 'date'])\nfast = full.groupby('ticker')['close'].transform(lambda s: s.ewm(span=5, adjust=False).mean())\nslow = full.groupby('ticker')['close'].transform(lambda s: s.ewm(span=20, adjust=False).mean())\nabove = (fast > slow).astype(bool)\nbefore = above.groupby(full['ticker']).shift(1)\nfull['up'] = above & (before == False)\nfull['down'] = ~above & (before == True)\nbt = backtest('prices', full, 'up', exit_signal='down', stop=0.05, target=0.10, name='cross')\nload('stock_classification')\nprint(bt['summary'][-1]['trades'])",
     "runnable": true,
     "title": "Moving-average cross with a stop, a target and an exit on the opposite cross"
    }
   ],
   "g": null,
   "helpers": [
    "backtest"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "backtest",
     "rule": "The price request (data request id or logical name)."
    },
    {
     "name": "frame",
     "of": "backtest",
     "rule": "Your frame with the request's entity and date columns and the signal columns; compute indicators on the whole frame, warm-up rows included."
    },
    {
     "name": "signal",
     "of": "backtest",
     "rule": "A boolean column: True on the bar whose close triggers an entry (filled at the next bar's open)."
    },
    {
     "default": null,
     "name": "exit_signal",
     "of": "backtest",
     "rule": "A boolean column: True on the bar whose close triggers an exit (filled at the next bar's open)."
    },
    {
     "default": null,
     "name": "stop",
     "of": "backtest",
     "rule": "Stop loss as a fraction of the entry price (0.05 for 5%)."
    },
    {
     "default": null,
     "name": "target",
     "of": "backtest",
     "rule": "Take profit as a fraction of the entry price (0.10 for 10%)."
    },
    {
     "default": null,
     "name": "max_hold",
     "of": "backtest",
     "rule": "Bars to hold at most (closed at the last bar's close)."
    },
    {
     "default": null,
     "name": "fee",
     "of": "backtest",
     "rule": "Cost per side as a fraction (0.0015 for 0.15%)."
    },
    {
     "default": null,
     "name": "unit",
     "of": "backtest",
     "rule": "PERCENT (default) or DECIMAL for the returns."
    },
    {
     "default": null,
     "name": "prices",
     "of": "backtest",
     "rule": "{'open', 'high', 'low', 'close'} -> the request's columns when named differently."
    },
    {
     "default": null,
     "name": "range_id",
     "of": "backtest",
     "rule": "One approved range (default: every range, each traded on its own)."
    },
    {
     "default": null,
     "name": "name",
     "of": "backtest",
     "rule": "The output name (backtest_<n> when omitted)."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "Long only, one position per entity; a signal while a position is open is skipped and counted.",
    "Stop and target are checked from the entry bar; a bar that opens beyond a level fills at its open; when both levels are inside one bar the stop is taken first.",
    "Only bars inside the approved ranges trade; a position still open at a range's end closes at its last close (OPEN_AT_END).",
    "Prices are read from the bundle, not from your frame; the frame gives the signal dates only."
   ],
   "name": "backtest",
   "results": "<name>_trades (entity, range_id, signal_date, entry_date, entry_price, exit_date, exit_price, exit_reason STOP, TARGET, EXIT_SIGNAL, MAX_HOLD or OPEN_AT_END, bars_held, return) and <name>_summary (per entity and ALL: signals, signals_skipped, trades, wins, win_rate, mean_return, median_return, average_win, average_loss, realized_reward_risk, profit_factor, cumulative_return, max_drawdown, bars_in_period, bars_buffer, first_date, last_date). Quote the trade count and the period's bars from <name>_summary; bars_buffer are warm-up rows, not sample. The call returns the trades frame and tables (each table's name, for load_output in a later run_python).",
   "title": "Backtest: trades of a stated entry and exit rule on the governed prices",
   "use_when": [
    "Testing a trading rule the user states or scripts (for example a Pine strategy): the trades, win rate, average gain and loss, realized reward to risk, profit factor and drawdown over the approved period."
   ],
   "verification": {
    "checked": [
     "complete_analysis re-runs the simulation on the bundle prices from the recorded signal dates and compares both tables; a match labels them CALCULATION_VERIFIED",
     "a released table that differs fails completion (CALCULATION_MISMATCH)"
    ],
    "level": "STATISTICS_VERIFIED",
    "not_checked": [
     "how your code computed the signals (the indicators and the crossing rule)"
    ]
   }
  },
  "guide_sha256": "f05b86061f613a1d6e61a8ab6503dc34e65220b5c9e36c21a6f4b272d2c9f626",
  "guides_version": 7,
  "kind": "HELPER",
  "name": "backtest"
 },
 {
  "g": "G3",
  "guide": {
   "avoid_when": [
    "One root hypothesis examined with several library methods (multi-angle plan).",
    "A description or calculation without a hypothesis (free code)."
   ],
   "common_errors": [
    {
     "code": "research findings MISSING",
     "fix": "call event_summary once per hypothesis before complete_analysis.",
     "seen_in": "research findings v1"
    },
    {
     "code": "RESEARCH_PLAN_MISMATCH",
     "fix": "copy hypothesis_id, hypothesis, objective, condition, outcome, baseline and the policy exactly from the approved experiment.",
     "seen_in": "research plan v1"
    }
   ],
   "examples": [
    {
     "code": "study = event_study('prices', 'close / lag(close, 1) - 1 <= -0.01', {'forward_return': 'close'}, 1, name='dips')\nload('stock_classification')\nresult = event_summary(study['events'], study['baseline'], hypothesis_id='dip_rebound', outcome_column='outcome', date_column='date')\nprint(result['verdict'])",
     "runnable": true,
     "title": "An event study's rows as a hypothesis"
    }
   ],
   "g": "G3",
   "helpers": [
    "event_summary"
   ],
   "inputs": [
    {
     "name": "experiments",
     "rule": "One to four, each with hypothesis_id, hypothesis, objective, condition, outcome, baseline, candidate_count, pairwise_comparisons, multiple_testing_policy, holdout_required, minimum sample, expected_direction, outcome_horizon_periods, outcome_unit, success_definition and min_effect (each threshold as the user wrote it, with its unit: min_effect_unit, success_rule.unit)."
    },
    {
     "name": "events",
     "of": "event_summary",
     "rule": "One row per occurrence of the condition with its outcome and date (your code, or an event study's events frame)."
    },
    {
     "name": "baseline",
     "of": "event_summary",
     "rule": "The comparison rows with outcome and date (your code, or an event study's baseline frame)."
    },
    {
     "name": "hypothesis_id",
     "of": "event_summary",
     "rule": "The approved experiment's hypothesis_id."
    },
    {
     "name": "outcome_column",
     "of": "event_summary",
     "rule": "The outcome column of both frames."
    },
    {
     "name": "date_column",
     "of": "event_summary",
     "rule": "The date column of both frames."
    },
    {
     "default": null,
     "name": "success_column",
     "of": "event_summary",
     "rule": "A boolean column for success; refused when the approved plan has a success_rule."
    },
    {
     "default": null,
     "name": "success_above",
     "of": "event_summary",
     "rule": "Leave unset: the approved plan's success_rule is applied by the backend (outcome above zero when the plan has none); a different value is refused."
    },
    {
     "default": 1,
     "name": "horizon_periods",
     "of": "event_summary",
     "rule": "Periods one outcome spans (overlapping outcomes count once)."
    },
    {
     "default": null,
     "name": "outcome_unit",
     "of": "event_summary",
     "rule": "Leave unset: the approved experiment's outcome_unit is used (a different one is refused)."
    },
    {
     "default": "HIGHER",
     "name": "expected_direction",
     "of": "event_summary",
     "rule": "HIGHER, LOWER or DIFFERENT."
    },
    {
     "default": null,
     "name": "min_effect",
     "of": "event_summary",
     "rule": "The smallest effect that matters, when the user named one."
    },
    {
     "default": 1,
     "name": "comparisons",
     "of": "event_summary",
     "rule": "Comparisons of the multiple-testing correction."
    },
    {
     "default": "NONE",
     "name": "multiple_testing_policy",
     "of": "event_summary",
     "rule": "NONE, BONFERRONI, HOLM or BENJAMINI_HOCHBERG."
    }
   ],
   "kind": "PATH",
   "limits": [
    "The user approves the plan before any data is used; check_data_feasibility first.",
    "Each RESEARCH data need copies research_governance from its approved experiment.",
    "The Research Governor bounds the hypotheses, experiments and follow-ups.",
    "A research analysis without event_summary for each hypothesis is not completed."
   ],
   "name": "hypothesis_plan",
   "results": "complete_analysis returns research_findings, one per hypothesis (verdict, sample category, angle_a difference with its interval, angle_b success shares). Cite {{finding.<hypothesis_id>.angle_a.difference}}; copy the verdict unchanged.",
   "title": "Hypothesis plan: hypotheses you formulate, tested with the backend's verdict",
   "use_when": [
    "One to four specific condition -> outcome hypotheses you formulate from the question and the data, each with a baseline, a verdict and a judgement of its sample.",
    "Testing an event study's events as a hypothesis."
   ],
   "verification": {
    "checked": [
     "the difference, interval, p-value, effective sample, smallest detectable effect, sample category and verdict are recomputed from the per-date aggregates of the rows passed to event_summary, with the approved values"
    ],
    "level": "STATISTICS_VERIFIED",
    "not_checked": [
     "how the events and baseline rows were built, unless they come from event_study, whose rows the backend rebuilt from its declaration"
    ]
   }
  },
  "guide_sha256": "aa58a70da9e0b62a153ccf0a5b039e5b938378eccfc748cecc645e8ceec1f003",
  "guides_version": 7,
  "kind": "PATH",
  "name": "hypothesis_plan"
 },
 {
  "g": "G4",
  "guide": {
   "avoid_when": [
    "A hypothesis no library method answers (hypothesis plan).",
    "A single calculation or event study (free code, event study)."
   ],
   "common_errors": [
    {
     "code": "OUTCOME_NOT_APPROVED",
     "fix": "the outcome is {'forward_return': '<price column>'}, never a price level.",
     "seen_in": "S15"
    },
    {
     "code": "PLAN_FEASIBILITY",
     "fix": "present exactly the angles and designs check_research_feasibility returned FEASIBLE.",
     "seen_in": "M49"
    }
   ],
   "examples": [
    {
     "code": "get_research_library -> check_research_feasibility -> RESEARCH_PLAN_CONFIRMATION -> (approval) start_research_run -> run_research_code: research_conditional('<angle_id>', request='<data_request_id>', condition='close / lag(close, 1) - 1 <= -0.05', outcome={'forward_return': 'close'}) -> complete_research_run",
     "runnable": false,
     "title": "The sequence of calls"
    }
   ],
   "g": "G4",
   "helpers": [],
   "inputs": [
    {
     "name": "angles",
     "rule": "Each angle: angle_id, its question, a method of get_research_library with its parameters, horizon, unit, comparisons, multiple-testing policy, holdout and, for a return outcome, the request and price column; checked with check_research_feasibility before the plan is shown."
    }
   ],
   "kind": "PATH",
   "limits": [
    "The negotiated number of angles per plan.",
    "Each angle is recorded once with its research helper in the approved bundle group.",
    "The user approves the plan before any data is used."
   ],
   "name": "multi_angle",
   "results": "complete_research_run returns one finding per angle and a synthesis map. Cite {{finding.<angle_id>.estimates.primary.estimate}}; copy each status unchanged.",
   "title": "Multi-angle plan: one root hypothesis from several library methods",
   "use_when": [
    "One root hypothesis examined from several angles, each answered by one method of the research library with its own status, and a synthesis of where the angles agree."
   ],
   "verification": {
    "checked": [
     "a declarative angle (expressions over a request) is rebuilt and recomputed by the backend"
    ],
    "level": "FORMULA_AND_STATISTICS_VERIFIED",
    "not_checked": [
     "an angle recorded from a frame your code built is checked only for staying inside its data contract (STATISTICS_VERIFIED)",
     "research_custom verifies execution only"
    ]
   }
  },
  "guide_sha256": "95fdd346b17182a50f6f1445e1884818306760b7a8b7e9f5cf2bff0ef7624d4b",
  "guides_version": 7,
  "kind": "PATH",
  "name": "multi_angle"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "A return between two dates the user gave, an event's forward return, a rolling return."
   ],
   "common_errors": [
    {
     "code": "NO_PRIOR_CLOSE",
     "fix": "the entity has no value before the period within the buffer: report it, do not fill it.",
     "seen_in": "D12"
    }
   ],
   "examples": [
    {
     "code": "ytd = period_return('prices', 'current_ytd')\nload('prices')\nload('stock_classification')\nemit_table('ytd', ytd, definition={})",
     "runnable": true,
     "title": "Year-to-date return per entity"
    }
   ],
   "g": null,
   "helpers": [
    "period_return"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "period_return",
     "rule": "The data request id or logical name; it needs a history buffer of one trading observation."
    },
    {
     "name": "range_id",
     "of": "period_return",
     "rule": "The approved range of the period."
    },
    {
     "default": "close",
     "name": "value_column",
     "of": "period_return",
     "rule": "The price column."
    },
    {
     "default": null,
     "name": "entity_column",
     "of": "period_return",
     "rule": "When the request's entity column is not the catalog's."
    },
    {
     "default": null,
     "name": "date_column",
     "of": "period_return",
     "rule": "When the request's time column is not the catalog's."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "The base is the last valid value strictly before the range start, the end the last valid value on or before its end.",
    "Without a history buffer it refuses (PeriodReturnError) instead of using the first value inside the period."
   ],
   "name": "period_return",
   "results": "One row per entity: base_date, base_value, end_date, end_value, return_decimal, return_pct and calculation_status (COMPLETE or why not); leave entities that are not COMPLETE out of rankings.",
   "title": "Return over a named calendar period (YTD, month, quarter, year)",
   "use_when": [
    "A return over a named calendar period, one row per entity, with one boundary convention."
   ],
   "verification": {
    "checked": [
     "the boundary convention and the return formula are the helper's tested code"
    ],
    "level": "BACKEND_HELPER",
    "not_checked": [
     "rankings or averages you compute from its rows"
    ]
   }
  },
  "guide_sha256": "fe5225dedf0104b9f46d39b01f610a2b1f126a5cfe38bb596bc04b0dc4aabecf",
  "guides_version": 7,
  "kind": "HELPER",
  "name": "period_return"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "A column without a catalog resample rule (ResampleRuleMissing): drop it or stay daily."
   ],
   "common_errors": [
    {
     "code": "ResampleRuleMissing",
     "fix": "the column has no catalog rule; keys of the request's grain are not value columns.",
     "seen_in": "P13"
    }
   ],
   "examples": [],
   "g": null,
   "helpers": [
    "resample"
   ],
   "inputs": [
    {
     "name": "frame",
     "of": "resample",
     "rule": "The daily rows (from load or load_range)."
    },
    {
     "name": "request",
     "of": "resample",
     "rule": "The data request id or logical name whose catalog rules apply."
    },
    {
     "default": null,
     "name": "frequency",
     "of": "resample",
     "rule": "The target frequency when the request declares none."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "Each column follows its catalog resample_aggregation (FIRST, LAST, MAX, MIN, SUM).",
    "Compare or rank only periods with period_complete true."
   ],
   "name": "resample",
   "results": "One row per entity and period with period_start, period_end, actual_first_date, actual_last_date, observations and period_complete.",
   "title": "Weekly or monthly rows from daily rows with the catalog's rules",
   "use_when": [
    "A weekly or monthly analysis of a daily request that declared resample."
   ],
   "verification": {
    "checked": [
     "the aggregation of each column is the catalog's rule in the helper's code"
    ],
    "level": "BACKEND_HELPER",
    "not_checked": [
     "what you compute from the periods"
    ]
   }
  },
  "guide_sha256": "40bade75a80b89747fd1441f62387254d490e5bdbe670fc719685919bf598790",
  "guides_version": 7,
  "kind": "HELPER",
  "name": "resample"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "A pandas merge you design yourself: its grain and point-in-time semantics are not checked."
   ],
   "common_errors": [
    {
     "code": "JoinCardinalityError",
     "fix": "preaggregate the many side to the relationship's key grain first.",
     "seen_in": "join"
    }
   ],
   "examples": [],
   "g": null,
   "helpers": [
    "join",
    "preaggregate"
   ],
   "inputs": [
    {
     "name": "relationship_id",
     "of": "join",
     "rule": "The approved relationship."
    },
    {
     "default": null,
     "name": "left",
     "of": "join",
     "rule": "A frame of the left request (default: all of it)."
    },
    {
     "default": null,
     "name": "right",
     "of": "join",
     "rule": "A frame of the right request (default: all of it)."
    },
    {
     "default": null,
     "name": "how",
     "of": "join",
     "rule": "inner or left (default: the relationship's join type)."
    },
    {
     "name": "relationship_id",
     "of": "preaggregate",
     "rule": "The relationship whose many side is reduced to its key grain."
    },
    {
     "default": null,
     "name": "frame",
     "of": "preaggregate",
     "rule": "The many side's rows (default: all of it)."
    },
    {
     "default": null,
     "name": "measures",
     "of": "preaggregate",
     "rule": "The columns to aggregate, each with the catalog's cross-entity rule."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "A column without a catalog cross-entity rule raises AggregationRuleMissing.",
    "A relationship that requires preaggregation accepts only preaggregate's result."
   ],
   "name": "join_and_preaggregate",
   "results": "A frame at the relationship's grain; join_report() gives matched and unmatched rows.",
   "title": "Joining two requests by an approved relationship",
   "use_when": [
    "Combining two requests of the bundle through a relationship the data need approved."
   ],
   "verification": {
    "checked": [
     "the join keys, cardinality and point-in-time semantics of the relationship"
    ],
    "level": "BACKEND_HELPER",
    "not_checked": [
     "the calculation after the join"
    ]
   }
  },
  "guide_sha256": "85469bb5938b70d3d0dab3193633c0243349d602b749aba88c1b5535a2d20040",
  "guides_version": 7,
  "kind": "HELPER",
  "name": "join_and_preaggregate"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "Reading the input files directly: it counts as not processed."
   ],
   "common_errors": [
    {
     "code": "MaterializationLimitExceeded",
     "fix": "GROUP BY the entity and date columns in sql() first.",
     "seen_in": "G14"
    },
    {
     "code": "SanitiError: 1 is not a data request",
     "fix": "plain range() is Python's; the helper is load_range.",
     "seen_in": "S21"
    }
   ],
   "examples": [
    {
     "code": "for table in carried():\n    print(table['output_id'], table['name'], table['kind'], table['label'])\nearlier = load_output('<output_id>')\nprint(earlier.attrs['label'])",
     "runnable": false,
     "title": "An earlier result as input, with its label"
    },
    {
     "code": "full = load('prices').sort_values(['ticker', 'date'])\nfull['ma5'] = full.groupby('ticker')['close'].transform(lambda s: s.rolling(5).mean())\ninside = full[in_period(full, 'prices')]\nload('stock_classification')\nemit_table('above_ma5', inside.assign(above=inside['close'] > inside['ma5']).groupby('ticker', as_index=False)['above'].sum(), definition={})",
     "runnable": true,
     "title": "Indicators on the whole history, counts over the approved ranges only"
    },
    {
     "code": "daily = sql('SELECT date, avg(close) AS mean_close FROM prices GROUP BY date ORDER BY date')\nprevious = load_range('prices', 'previous_comparable')\nload('prices')\nload('stock_classification')\nemit_table('daily_mean', daily, definition={})",
     "runnable": true,
     "title": "A summary in DuckDB, then one range in pandas"
    }
   ],
   "g": null,
   "helpers": [
    "load",
    "load_range",
    "in_period",
    "sql",
    "load_output",
    "carried"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "load",
     "rule": "The data request id or logical name."
    },
    {
     "default": null,
     "name": "columns",
     "of": "load",
     "rule": "Columns to read (default: all)."
    },
    {
     "name": "request",
     "of": "load_range",
     "rule": "The data request id or logical name."
    },
    {
     "name": "range_id",
     "of": "load_range",
     "rule": "One approved range."
    },
    {
     "default": null,
     "name": "columns",
     "of": "load_range",
     "rule": "Columns to read (default: all)."
    },
    {
     "default": false,
     "name": "include_buffers",
     "of": "load_range",
     "rule": "True widens the range to its warm-up and future buffers."
    },
    {
     "name": "frame",
     "of": "in_period",
     "rule": "A frame with the request's date column (for example from load or include_buffers=True)."
    },
    {
     "name": "request",
     "of": "in_period",
     "rule": "The data request id or logical name."
    },
    {
     "default": null,
     "name": "range_id",
     "of": "in_period",
     "rule": "One approved range (default: every range)."
    },
    {
     "default": null,
     "name": "date_column",
     "of": "in_period",
     "rule": "The frame's date column (default: the request's)."
    },
    {
     "name": "query",
     "of": "sql",
     "rule": "DuckDB SQL over one view per logical name."
    },
    {
     "default": null,
     "name": "params",
     "of": "sql",
     "rule": "Query parameters."
    },
    {
     "name": "output_id",
     "of": "load_output",
     "rule": "A released table of this conversation (an analysis table, an event study's tables, a hypothesis plan's aggregates, a multi-angle angle's input), from carried() or the data record."
    },
    {
     "default": null,
     "name": "columns",
     "of": "load_output",
     "rule": "Columns to read (default: all)."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "A request shown as AGGREGATE_FIRST is reduced in sql() before it becomes a pandas frame.",
    "Every approved request and range must be read before complete_analysis.",
    "Row counts name their span: rows_extracted (everything delivered, buffers included), rows_in_ranges and ranges[].rows (inside the approved ranges), ranges[].buffer_rows_before and buffer_rows_after. A sample size uses the rows inside the ranges: frame[in_period(frame, request)].",
    "A research plan's session loads only the carried tables its approved plan names; an analysis session loads any released table of the conversation (24 hours)."
   ],
   "name": "reading_data",
   "results": "pandas frames; the time column holds datetime.date objects and numbers are float64; a carried frame's attrs hold its label and origin.",
   "title": "Reading the bundle: load, load_range, in_period and sql",
   "use_when": [
    "Every read of the approved data; sql() first for large requests (summaries in DuckDB)."
   ],
   "verification": {
    "checked": [
     "what was read, per request and range, for coverage",
     "which carried tables were loaded (carried_inputs of the final status, with their labels)"
    ],
    "level": "DATA_COVERAGE_VERIFIED",
    "not_checked": [
     "the SQL or pandas logic"
    ]
   }
  },
  "guide_sha256": "8364e6ebdd4076d640cb3c8abdd21e8fdbed688f16660fa1cd390b2987424ee7",
  "guides_version": 7,
  "kind": "HELPER",
  "name": "reading_data"
 }
]$guides$::jsonb) AS r(
    name text, guides_version integer, kind text, g text, guide jsonb, guide_sha256 text);

UPDATE public."Table_Catalog"
SET source_code_paths = (SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(source_code_paths || ARRAY[
        'database/migrations/20261009_005_ai_method_guides_v7.sql']) AS p)
WHERE table_schema = 'public' AND table_name = 'AI_method_guide';

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."AI_method_guide" WHERE is_active AND guides_version = 7
          AND guides_sha256 = '2863d4073a1d12aa456ced7082a5355d0a5065903f1e89abfb2f6164b74a5968') <> 9 THEN
        RAISE EXCEPTION 'Expected 9 active method guide rows of version 7 with the guides hash';
    END IF;
    IF (SELECT count(DISTINCT g) FROM public."AI_method_guide" WHERE kind = 'PATH' AND guides_version = 7) <> 4 THEN
        RAISE EXCEPTION 'Expected one guide for each of G1, G2, G3 and G4';
    END IF;
END
$verify$;
COMMIT;
