-- EXEC.md EXEC-Y (user decisions 2026-10-09: "Ok untuk B semua link web hilang pindah ke source"; "E1 ok 2-4"; go "gas"): the tool contracts the code now offers.
-- research_web v2: a web value is shown without a link and its source page is listed in the answer's
-- Sources panel (user decision B 2026-10-09). export_result v3: the XLSX definition sheet says what
-- one row is and, from one SQL Governor summary over the file's own period, how complete each group
-- is against the source table (EXEC-Y Fase 3 E1).
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN (('research_web', 'v1'), ('export_result', 'v2'))) <> 2 THEN
        RAISE EXCEPTION 'Expected the previous tool versions (''research_web'', ''v1''), (''export_result'', ''v2'')';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE (tool_name = 'research_web' AND version = 'v2') OR (tool_name = 'export_result' AND version = 'v3')) THEN
        RAISE EXCEPTION 'The EXEC-Y Fase 3 and decision B tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{"completeness":"one Governor summary (COUNT) per export, at most 6 group columns and 50 groups; a filter through another table or one longer than 2,000 characters is not checked and the file says so","design":"EXEC.md EXEC-Y Fase 3 and decision B; ERRORS_AND_SOLUTIONS.md M128 (d), M132","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here"}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
    ('research_web', 'v1', 'v2', '{"additionalProperties":false,"properties":{"expected_shape":{"anyOf":[{"enum":["FACT","NUMBER","EVENT","SERIES","LIST"],"type":"string"},{"type":"null"}],"description":"The shape the answer should have, or null when not known."},"need":{"description":"What to find, in words, e.g. ''nilai ekspor Indonesia per tahun sejak 2018''.","type":"string"},"purpose":{"description":"CITE: values to state in the answer; CONTEXT: background for an analysis of the data.","enum":["CITE","CONTEXT"],"type":"string"},"subjects":{"description":"Companies or entities the same need is asked about, one lookup each; empty for one need.","items":{"type":"string"},"type":"array"}},"required":["need","purpose","expected_shape","subjects"],"type":"object"}',
     'Information that is not in the market database, from the web, for context or when the database lacks it: a fact, a figure, an event with its dates, a series over periods (for example yearly exports) or a list (for example the banks a group controls). Give one need in words, its purpose (CITE a value in the answer, CONTEXT for an analysis) and the expected shape when you know it; the same need about several companies is one call with them as subjects. The web governor searches, keeps only items quoted verbatim from their sources, labels false conflicts (different periods, definitions, units or releases) and, for a real conflict, the version it prefers (chosen_by_ai) with every version kept. Never use it for prices, volumes, flows or any figure the database holds; a web number describes and is never an input of a calculation, while an event date may set an analysis period. A run has a limited web budget: ask for what the answer needs. Each item has a ref: cite a number as {{<ref>.value_as_written}} (as its source writes it) or {{<ref>.value}} (the value at full scale), and a list or a short value as {{<ref>.value}}; the text shows the value without a link, and its source page is listed in the answer''s Sources panel. A fact''s statement is never inserted: say it in the reader''s language, in your own words, and put {{<ref>.value}} right after it, which shows nothing in the text and records the statement''s source; a figure the statement or its quote gives ("5,1%") may be written in those words, and it is checked against that quote. An attribute the database''s reference tables hold (sector, industry, company profile) is read with lookup_reference; this tool is refused for it until those tables have been read.'),
    ('export_result', 'v2', 'v3', '{"additionalProperties":false,"properties":{"column_labels":{"anyOf":[{"items":{"additionalProperties":false,"properties":{"column":{"description":"The column''s name in the output.","type":"string"},"label":{"description":"Its title in the user''s language.","type":"string"}},"required":["column","label"],"type":"object"},"type":"array"},{"type":"null"}],"description":"XLSX: the title the reader sees for each column, in the user''s language; a column not named keeps its name made readable."},"evidence_id":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"A checked claim''s evidence rows."},"format":{"enum":["CSV","XLSX","PARQUET"],"type":"string"},"include_definition":{"anyOf":[{"type":"boolean"},{"type":"null"}],"description":"XLSX: a sheet with the output''s definition (default true)."},"include_lineage":{"anyOf":[{"type":"boolean"},{"type":"null"}],"description":"XLSX: a sheet with where the data came from (default true)."},"output_id":{"anyOf":[{"type":"string"},{"type":"null"}]},"ref":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"The output''s value reference."}},"required":["ref","output_id","evidence_id","format","include_definition","include_lineage","column_labels"],"type":"object"}',
     'Write an output as a file the user downloads (CSV, XLSX with definition and lineage sheets, or PARQUET), at most 20 MB. Give ref (out.o3), output_id, or evidence_id (a checked claim''s evidence rows). Returns export_id, file name, size and format only; the answer names the file, the user downloads it. For XLSX give column_labels: the title of each column in the user''s language, as the reader should see it. The backend adds to the XLSX definition sheet what one row is and how complete each group is against the source table.')
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ((tool_name = 'research_web' AND version = 'v2') OR (tool_name = 'export_result' AND version = 'v3'))) <> 2 THEN
        RAISE EXCEPTION 'The EXEC-Y Fase 3 and decision B tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'research_web' AND version = 'v2' AND purpose::text LIKE '%Sources panel%')
       OR NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'export_result' AND version = 'v3' AND purpose::text LIKE '%how complete each group is%') THEN
        RAISE EXCEPTION 'The EXEC-Y Fase 3 and decision B contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
