-- EXEC.md EXEC-E and EXEC-R (user approval 2026-10-06): the tool contracts the code now offers.
-- query_metric v2: a period may start without an end and then runs to as_of (EXEC-R R5c; golden test
-- ma-qa-20261006b refused four parallel calls for it, M88). get_evidence: removed from the code
-- (EXEC-E, user decision 2026-10-06); its rows stay and carry the removal. Table_Catalog:
-- AI_conversation_evidence is no longer written.
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN (('query_metric', 'v1'))) <> 1 THEN
        RAISE EXCEPTION 'Expected the previous tool versions (''query_metric'', ''v1'')';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE (tool_name = 'query_metric' AND version = 'v2')) THEN
        RAISE EXCEPTION 'The EXEC-E and EXEC-R tool versions are already registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'get_evidence')
       OR EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'get_evidence' AND tool_specific_limits ? 'removed')
       OR (SELECT count(*) FROM public."Table_Catalog" WHERE table_schema = 'public' AND table_name = 'AI_conversation_evidence' AND update_rule NOT LIKE '%Not written since%') <> 1 THEN
        RAISE EXCEPTION 'The removed tools or their tables are missing or already marked';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{"design":"EXEC.md EXEC-E and EXEC-R (user approval 2026-10-06)","period":"trading_days, or start_date with end_date optional (null: up to as_of)","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here"}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
    ('query_metric', 'v1', 'v2', '{"additionalProperties":false,"properties":{"as_of":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"Last date of trading-day periods; null: the conversation''s data date, else today."},"dimensions":{"anyOf":[{"items":{"type":"string"},"type":"array"},{"type":"null"}],"description":"Split by these dimensions; null: the default."},"entities":{"anyOf":[{"items":{"type":"string"},"type":"array"},{"type":"null"}],"description":"Entity values (e.g. tickers)."},"filters":{"anyOf":[{"items":{"additionalProperties":false,"properties":{"column":{"type":"string"},"values":{"items":{"type":"string"},"type":"array"}},"required":["column","values"],"type":"object"},"type":"array"},{"type":"null"}],"description":"Equality filters on dimensions of the metric."},"metric":{"description":"A metric id from the METRICS note.","type":"string"},"periods":{"items":{"additionalProperties":false,"properties":{"end_date":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"A date range end; null: up to as_of (the latest data)."},"start_date":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"A date range start."},"trading_days":{"anyOf":[{"type":"integer"},{"type":"null"}],"description":"The last N trading days up to as_of."}},"required":["trading_days","start_date","end_date"],"type":"object"},"type":"array"}},"required":["metric","entities","filters","dimensions","periods","as_of"],"type":"object"}',
     'An official metric (listed in the METRICS note) for entities over periods, computed by the database in one summary per period: periods are trading days of the table''s own calendar up to as_of (the conversation''s data date by default) or a date range. Returns rows per dimension with days_present, first_date and last_date, and a metric ref to cite. Not for statistics, rankings across many entities or formulas: use submit_data_need_spec.')
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

UPDATE public."Tool_Catalog" SET tool_specific_limits = tool_specific_limits || '{"removed":"2026-10-06: removed from market-ai-orc with its switch AI_ENABLE_EVIDENCE and its gate (EXEC.md EXEC-E, user decision); cited figures are written by their address (DIRUJUK) instead"}'::jsonb,
    is_active = false
WHERE tool_name = 'get_evidence';
UPDATE public."Table_Catalog" SET update_rule = update_rule || ' Not written since 2026-10-06: get_evidence was removed from market-ai-orc (EXEC-E); the rows stay with their conversation.'
WHERE table_schema = 'public' AND table_name = 'AI_conversation_evidence';

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ((tool_name = 'query_metric' AND version = 'v2'))) <> 1 THEN
        RAISE EXCEPTION 'The EXEC-E and EXEC-R tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'query_metric' AND version = 'v2' AND input_schema::text LIKE '%null: up to as_of%') THEN
        RAISE EXCEPTION 'The EXEC-E and EXEC-R contracts are not in the registered rows';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'get_evidence' AND (is_active OR NOT tool_specific_limits ? 'removed'))
       OR NOT EXISTS (SELECT 1 FROM public."Table_Catalog" WHERE table_schema = 'public' AND table_name = 'AI_conversation_evidence' AND update_rule LIKE '%Not written since 2026-10-06%') THEN
        RAISE EXCEPTION 'The removed tools or their tables were not marked';
    END IF;
END
$verify$;

COMMIT;
