-- Method guides (G2_G3_REACTIVATION_PLAN.md 4b, user decision 2026-10-02): the model-facing menu and manual of the
-- analysis paths (G1 free code, G2 event study, G3 hypothesis plan, G4 multi-angle plan) and of the main session
-- helpers. public."AI_method_guide" holds one row per guide; market-ai-orc offers the menu at the start of every run
-- and serves a guide through get_method_guide, only when the table, the sandbox and its own copy carry the same hash.
-- It describes, it does not compute. Tool_Catalog registers get_method_guide v1 (inactive like every market-ai-orc
-- row).
-- GENERATED by scripts/generate_ai_method_guide_migration.py from apps/market-python-sandbox/app/method_guides.py
-- (guides_sha256 d4a032ad33be15326b18a002e9b4044913b00a4b547f65917fc8f82b953cdf58); the sandbox test tests/test_method_guides.py fails on drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF to_regclass('public."AI_method_guide"') IS NOT NULL THEN
        RAISE EXCEPTION 'AI_method_guide already exists';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_ai_catalog_reader') THEN
        RAISE EXCEPTION 'market_ai_catalog_reader role is required';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'get_method_guide') THEN
        RAISE EXCEPTION 'get_method_guide is already registered';
    END IF;
END
$preflight$;

CREATE TABLE public."AI_method_guide" (
    name text NOT NULL,
    guides_version integer NOT NULL,
    kind text NOT NULL,
    g text,
    guide jsonb NOT NULL,
    guide_sha256 text NOT NULL,
    guides_sha256 text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AI_method_guide_pkey" PRIMARY KEY (name, guides_version),
    CONSTRAINT ai_method_guide_kind CHECK (kind IN ('PATH', 'HELPER')),
    CONSTRAINT ai_method_guide_g CHECK (g IS NULL OR g IN ('G1', 'G2', 'G3', 'G4')),
    CONSTRAINT ai_method_guide_path_has_g CHECK ((kind = 'PATH') = (g IS NOT NULL)),
    CONSTRAINT ai_method_guide_sha CHECK (guide_sha256 ~ '^[0-9a-f]{64}$' AND guides_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ai_method_guide_json CHECK (jsonb_typeof(guide) = 'object' AND guide->>'name' = name),
    CONSTRAINT ai_method_guide_name CHECK (name ~ '^[a-z][a-z0-9_]{0,62}$')
);
COMMENT ON TABLE public."AI_method_guide" IS
    'Model-facing menu and manual of the analysis paths and session helpers; generated from code, hash-bound '
    '(guides_sha256). Enforcement stays in code.';

-- market-ai-orc's catalog login inherits this role; the SQL Governor role gets no grant.
GRANT SELECT ON public."AI_method_guide" TO market_ai_catalog_reader;
REVOKE ALL ON public."AI_method_guide" FROM PUBLIC;

INSERT INTO public."AI_method_guide" (name, guides_version, kind, g, guide, guide_sha256, guides_sha256)
SELECT r.name, r.guides_version, r.kind, r.g, r.guide, r.guide_sha256, 'd4a032ad33be15326b18a002e9b4044913b00a4b547f65917fc8f82b953cdf58'
FROM jsonb_to_recordset($guides$[
 {
  "g": "G1",
  "guide": {
   "avoid_when": [
    "The outcome after an event, when event_study is offered (its result is recalculated by the backend).",
    "Testing a hypothesis with a verdict: that needs a research plan the user approves."
   ],
   "common_errors": [
    {
     "code": "SanitiError: 1 is not a data request",
     "fix": "range(n) is Python's built-in; one approved range is load_range(request, range_id) or saniti.range.",
     "seen_in": "S21"
    },
    {
     "code": "MaterializationLimitExceeded",
     "fix": "aggregate in sql() (GROUP BY the entity and date columns) before loading into pandas.",
     "seen_in": "G14"
    },
    {
     "code": "TypeError on a date comparison",
     "fix": "the time column holds datetime.date objects: compare with datetime.date or convert with pd.to_datetime first.",
     "seen_in": "2026-09-26 stress test"
    },
    {
     "code": "a unit shown twice",
     "fix": "a format such as pct, pp or rp already shows its unit: do not type it after the reference.",
     "seen_in": "P22"
    }
   ],
   "examples": [
    {
     "code": "top = sql('SELECT ticker, max(close) AS high, min(close) AS low FROM prices GROUP BY ticker ORDER BY high DESC')\nload('stock_classification')\nemit_table('high_low', top)",
     "runnable": true,
     "title": "Ranking from a SQL summary"
    },
    {
     "code": "now = load_range('prices', 'current_ytd')\nbefore = load_range('prices', 'previous_comparable')\nload('stock_classification')\nchange = (now.groupby('ticker')['close'].last() - before.groupby('ticker')['close'].last()).rename('change')\nshare = (change / change.abs().sum()).rename('share_of_total_move')\nemit_table('drivers', pd.concat([change, share], axis=1).sort_values('change'))",
     "runnable": true,
     "title": "Contribution of each entity to a change between two ranges"
    }
   ],
   "g": "G1",
   "helpers": [],
   "inputs": [
    {
     "name": "code",
     "rule": "Python for run_python. Read data only through the saniti helpers (load, load_range, sql, join, preaggregate, resample, period_return); a read outside them counts as not processed."
    }
   ],
   "insight": [
    "Answer why with a computed breakdown, not a guess: change between periods, top and bottom contributors, the measure split by a dimension, unusual values, concentration.",
    "Split only by catalog columns that are groupable; add values only where the catalog's aggregation rule is SUM.",
    "Compare with a baseline (other entities, other periods) and size the difference.",
    "Call the result an association, not a cause; causes outside the database (news, corporate actions) are not available; offer a test (event study or a research plan) when the user wants evidence."
   ],
   "kind": "PATH",
   "limits": [
    "A frame larger than the session's frame budget is refused before it loads (MaterializationLimitExceeded): reduce it in sql() first; the session and its variables stay.",
    "A table of an earlier result is loaded with load_output(output_id) (carried() lists them with their labels); a figure built on it is never better checked than its label.",
    "complete_analysis needs every approved request and range read in a successful execution and at least one output.",
    "Only released outputs may be cited; print() is diagnostics only."
   ],
   "name": "free_code",
   "results": "Released outputs of complete_analysis, cited as value references such as {{out.o1.rows[<column>=<value>].<column>}}.",
   "title": "Free analysis code in the session",
   "use_when": [
    "A calculation, ranking, screen, description or comparison that no other method covers.",
    "Explaining a result (why, what drives it, what stands out) by computing it from the data and outputs already in the session.",
    "Exploring the data first: each dataset's profile (in the session view) shows its columns, ranges, frequent values and sample rows; print or inspect more before deciding the method."
   ],
   "verification": {
    "checked": [
     "every approved request and range was delivered and read",
     "every figure of the answer comes from a released output (value references)"
    ],
    "level": "DATA_COVERAGE_VERIFIED",
    "not_checked": [
     "the formula of your code: say that the calculation was not independently recalculated"
    ]
   }
  },
  "guide_sha256": "523ea0bb9b0cbe3a3c5e152e71e99de2ea4ccb08f864d63b0a9e1d573953901c",
  "guides_version": 1,
  "kind": "PATH",
  "name": "free_code"
 },
 {
  "g": "G2",
  "guide": {
   "avoid_when": [
    "A request with more than one row per entity and date (for example per broker): reduce it to one row per entity and date first, or use another request.",
    "A verdict on a hypothesis: pass the events to a hypothesis plan."
   ],
   "common_errors": [
    {
     "code": "DUPLICATE_ENTITY_DATE",
     "fix": "use a request with one row per entity and date, or narrow its scope.",
     "seen_in": "event_study"
    },
    {
     "code": "EXPRESSION_INVALID",
     "fix": "use only the request's columns and the expression functions; the name in the message is the one that is unknown.",
     "seen_in": "event_study"
    },
    {
     "code": "CALCULATION_MISMATCH",
     "fix": "never overwrite or re-emit the study's tables; run event_study again under the same name.",
     "seen_in": "event_study"
    },
    {
     "code": "a price level as the outcome",
     "fix": "the outcome is {'forward_return': '<price column>'}; the backend computes the return.",
     "seen_in": "S15"
    }
   ],
   "examples": [
    {
     "code": "study = event_study('prices', 'close / lag(close, 1) - 1 <= -0.05', {'forward_return': 'close'}, 5, name='drops')\nload('stock_classification')\nprint(study['summary'][0]['event_count'])",
     "runnable": true,
     "title": "Five-day return after a fall of at least five percent"
    },
    {
     "code": "study = event_study('prices', 'close > rolling_mean(close, 5)', {'forward_return': 'close'}, 1, range_id='current_ytd', overlap_policy='ALL', baseline='NON_EVENT', name='above_mean')\nload('prices')\nload('stock_classification')",
     "runnable": true,
     "title": "One range, every event, compared with the days without an event"
    }
   ],
   "g": "G2",
   "helpers": [
    "event_study"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "event_study",
     "rule": "The data request id or logical name."
    },
    {
     "name": "event",
     "of": "event_study",
     "rule": "A condition, an expression over the request's columns, per entity and past values only: + - * / **, comparisons, & | ~, abs log exp sqrt sign min max where, lag(x, k), rolling_sum(x, n), rolling_mean(x, n); for example close / lag(close, 1) - 1 <= -0.05."
    },
    {
     "name": "outcome",
     "of": "event_study",
     "rule": "{'forward_return': '<price column>'}; add 'request': '<data request id>' when the price is in another request. Never a price level or a trailing return column."
    },
    {
     "name": "horizon",
     "of": "event_study",
     "rule": "Observations the outcome spans (one to two hundred sixty)."
    },
    {
     "default": null,
     "name": "range_id",
     "of": "event_study",
     "rule": "One approved range, or every range (each range is studied on its own window)."
    },
    {
     "default": "NON_OVERLAPPING",
     "name": "overlap_policy",
     "of": "event_study",
     "rule": "NON_OVERLAPPING keeps an entity's next event only a horizon after the last one it kept; ALL keeps every event."
    },
    {
     "default": "ALL_ELIGIBLE",
     "name": "baseline",
     "of": "event_study",
     "rule": "ALL_ELIGIBLE (every row with a defined condition and outcome) or NON_EVENT (the rows without the event)."
    },
    {
     "default": null,
     "name": "min_events",
     "of": "event_study",
     "rule": "The policy minimum reported as meets_min_events (default thirty); it never drops the study."
    },
    {
     "default": null,
     "name": "holdout_start",
     "of": "event_study",
     "rule": "A date YYYY-MM-DD: adds IN_SAMPLE and OUT_OF_SAMPLE rows."
    },
    {
     "default": "PERCENT",
     "name": "outcome_unit",
     "of": "event_study",
     "rule": "PERCENT or DECIMAL."
    },
    {
     "default": null,
     "name": "name",
     "of": "event_study",
     "rule": "The output name (event_study_<n> when omitted)."
    }
   ],
   "kind": "PATH",
   "limits": [
    "One row per entity and date (DUPLICATE_ENTITY_DATE otherwise).",
    "Ranges of the request may not overlap (RANGES_OVERLAP); choose one with range_id.",
    "An event whose outcome runs past the delivered data is censored and counted apart.",
    "The request is loaded whole, so it must fit the session's frame budget."
   ],
   "name": "event_study",
   "results": "Two tables: <name> (one row per segment ALL, IN_SAMPLE, OUT_OF_SAMPLE: event_count, event_dates, effective_event_dates, mean, median, hit_rate, baseline_count, baseline_mean, baseline_median, delta_mean, delta_ci_low, delta_ci_high, delta_p_value, censored_count, overlapping_dropped, meets_min_events) and <name>_events (date, entity, outcome); the call also returns the events and baseline frames. Cite {{out.o1.rows[segment=ALL].delta_mean}}. The interval and p-value treat events on one date as one observation.",
   "title": "Event study: the outcome after an event against a baseline",
   "use_when": [
    "What happened after an event (a fall, a spike, a flow above a level): the forward return after it against a baseline, with the number of events and its uncertainty.",
    "Building the events and baseline rows of a hypothesis plan."
   ],
   "verification": {
    "checked": [
     "complete_analysis rebuilds the events and outcomes from the declaration and the bundle files and recomputes both tables; a match labels them CALCULATION_VERIFIED",
     "a released table that differs fails completion (CALCULATION_MISMATCH)"
    ],
    "level": "FORMULA_AND_STATISTICS_VERIFIED",
    "not_checked": [
     "anything you compute afterwards from the tables or frames in your own code"
    ]
   }
  },
  "guide_sha256": "61e5ce75c71bb12254e4a7c90d6031982f406760faf0a4dc927cea046642e468",
  "guides_version": 1,
  "kind": "PATH",
  "name": "event_study"
 },
 {
  "g": "G3",
  "guide": {
   "avoid_when": [
    "One root hypothesis examined with several library methods (multi-angle plan).",
    "A description or calculation without a hypothesis (free code)."
   ],
   "common_errors": [
    {
     "code": "research findings MISSING",
     "fix": "call event_summary once per hypothesis before complete_analysis.",
     "seen_in": "research findings v1"
    },
    {
     "code": "RESEARCH_PLAN_MISMATCH",
     "fix": "copy hypothesis_id, hypothesis, objective, condition, outcome, baseline and the policy exactly from the approved experiment.",
     "seen_in": "research plan v1"
    }
   ],
   "examples": [
    {
     "code": "study = event_study('prices', 'close / lag(close, 1) - 1 <= -0.01', {'forward_return': 'close'}, 1, name='dips')\nload('stock_classification')\nresult = event_summary(study['events'], study['baseline'], hypothesis_id='dip_rebound', outcome_column='outcome', date_column='date')\nprint(result['verdict'])",
     "runnable": true,
     "title": "An event study's rows as a hypothesis"
    }
   ],
   "g": "G3",
   "helpers": [
    "event_summary"
   ],
   "inputs": [
    {
     "name": "experiments",
     "rule": "One to four, each with hypothesis_id, hypothesis, objective, condition, outcome, baseline, candidate_count, pairwise_comparisons, multiple_testing_policy, holdout_required, minimum sample, expected_direction, outcome_horizon_periods, outcome_unit, success_definition and min_effect."
    },
    {
     "name": "events",
     "of": "event_summary",
     "rule": "One row per occurrence of the condition with its outcome and date (your code, or an event study's events frame)."
    },
    {
     "name": "baseline",
     "of": "event_summary",
     "rule": "The comparison rows with outcome and date (your code, or an event study's baseline frame)."
    },
    {
     "name": "hypothesis_id",
     "of": "event_summary",
     "rule": "The approved experiment's hypothesis_id."
    },
    {
     "name": "outcome_column",
     "of": "event_summary",
     "rule": "The outcome column of both frames."
    },
    {
     "name": "date_column",
     "of": "event_summary",
     "rule": "The date column of both frames."
    },
    {
     "default": null,
     "name": "success_column",
     "of": "event_summary",
     "rule": "A boolean column for success; else outcome > success_above."
    },
    {
     "default": 0.0,
     "name": "success_above",
     "of": "event_summary",
     "rule": "The success threshold when there is no success column."
    },
    {
     "default": 1,
     "name": "horizon_periods",
     "of": "event_summary",
     "rule": "Periods one outcome spans (overlapping outcomes count once)."
    },
    {
     "default": "PERCENT",
     "name": "outcome_unit",
     "of": "event_summary",
     "rule": "PERCENT, DECIMAL or OTHER."
    },
    {
     "default": "HIGHER",
     "name": "expected_direction",
     "of": "event_summary",
     "rule": "HIGHER, LOWER or DIFFERENT."
    },
    {
     "default": null,
     "name": "min_effect",
     "of": "event_summary",
     "rule": "The smallest effect that matters, when the user named one."
    },
    {
     "default": 1,
     "name": "comparisons",
     "of": "event_summary",
     "rule": "Comparisons of the multiple-testing correction."
    },
    {
     "default": "NONE",
     "name": "multiple_testing_policy",
     "of": "event_summary",
     "rule": "NONE, BONFERRONI, HOLM or BENJAMINI_HOCHBERG."
    }
   ],
   "kind": "PATH",
   "limits": [
    "The user approves the plan before any data is used; check_data_feasibility first.",
    "Each RESEARCH data need copies research_governance from its approved experiment.",
    "The Research Governor bounds the hypotheses, experiments and follow-ups.",
    "A research analysis without event_summary for each hypothesis is not completed."
   ],
   "name": "hypothesis_plan",
   "results": "complete_analysis returns research_findings, one per hypothesis (verdict, sample category, angle_a difference with its interval, angle_b success shares). Cite {{finding.<hypothesis_id>.angle_a.difference}}; copy the verdict unchanged.",
   "title": "Hypothesis plan: hypotheses you formulate, tested with the backend's verdict",
   "use_when": [
    "One to four specific condition -> outcome hypotheses you formulate from the question and the data, each with a baseline, a verdict and a judgement of its sample.",
    "Testing an event study's events as a hypothesis."
   ],
   "verification": {
    "checked": [
     "the difference, interval, p-value, effective sample, smallest detectable effect, sample category and verdict are recomputed from the per-date aggregates of the rows passed to event_summary, with the approved values"
    ],
    "level": "STATISTICS_VERIFIED",
    "not_checked": [
     "how the events and baseline rows were built, unless they come from event_study, whose rows the backend rebuilt from its declaration"
    ]
   }
  },
  "guide_sha256": "f9e28c8fd9878d018560759ca0ac6f674d11e19650704fd19c791d97afe2bcad",
  "guides_version": 1,
  "kind": "PATH",
  "name": "hypothesis_plan"
 },
 {
  "g": "G4",
  "guide": {
   "avoid_when": [
    "A hypothesis no library method answers (hypothesis plan).",
    "A single calculation or event study (free code, event study)."
   ],
   "common_errors": [
    {
     "code": "OUTCOME_NOT_APPROVED",
     "fix": "the outcome is {'forward_return': '<price column>'}, never a price level.",
     "seen_in": "S15"
    },
    {
     "code": "PLAN_FEASIBILITY",
     "fix": "present exactly the angles and designs check_research_feasibility returned FEASIBLE.",
     "seen_in": "M49"
    }
   ],
   "examples": [
    {
     "code": "get_research_library -> check_research_feasibility -> RESEARCH_PLAN_CONFIRMATION -> (approval) start_research_run -> run_research_code: research_conditional('<angle_id>', request='<data_request_id>', condition='close / lag(close, 1) - 1 <= -0.05', outcome={'forward_return': 'close'}) -> complete_research_run",
     "runnable": false,
     "title": "The sequence of calls"
    }
   ],
   "g": "G4",
   "helpers": [],
   "inputs": [
    {
     "name": "angles",
     "rule": "Each angle: angle_id, its question, a method of get_research_library with its parameters, horizon, unit, comparisons, multiple-testing policy, holdout and, for a return outcome, the request and price column; checked with check_research_feasibility before the plan is shown."
    }
   ],
   "kind": "PATH",
   "limits": [
    "The negotiated number of angles per plan.",
    "Each angle is recorded once with its research helper in the approved bundle group.",
    "The user approves the plan before any data is used."
   ],
   "name": "multi_angle",
   "results": "complete_research_run returns one finding per angle and a synthesis map. Cite {{finding.<angle_id>.estimates.primary.estimate}}; copy each status unchanged.",
   "title": "Multi-angle plan: one root hypothesis from several library methods",
   "use_when": [
    "One root hypothesis examined from several angles, each answered by one method of the research library with its own status, and a synthesis of where the angles agree."
   ],
   "verification": {
    "checked": [
     "a declarative angle (expressions over a request) is rebuilt and recomputed by the backend"
    ],
    "level": "FORMULA_AND_STATISTICS_VERIFIED",
    "not_checked": [
     "an angle recorded from a frame your code built is checked only for staying inside its data contract (STATISTICS_VERIFIED)",
     "research_custom verifies execution only"
    ]
   }
  },
  "guide_sha256": "95fdd346b17182a50f6f1445e1884818306760b7a8b7e9f5cf2bff0ef7624d4b",
  "guides_version": 1,
  "kind": "PATH",
  "name": "multi_angle"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "A return between two dates the user gave, an event's forward return, a rolling return."
   ],
   "common_errors": [
    {
     "code": "NO_PRIOR_CLOSE",
     "fix": "the entity has no value before the period within the buffer: report it, do not fill it.",
     "seen_in": "D12"
    }
   ],
   "examples": [
    {
     "code": "ytd = period_return('prices', 'current_ytd')\nload('prices')\nload('stock_classification')\nemit_table('ytd', ytd)",
     "runnable": true,
     "title": "Year-to-date return per entity"
    }
   ],
   "g": null,
   "helpers": [
    "period_return"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "period_return",
     "rule": "The data request id or logical name; it needs a history buffer of one trading observation."
    },
    {
     "name": "range_id",
     "of": "period_return",
     "rule": "The approved range of the period."
    },
    {
     "default": "close",
     "name": "value_column",
     "of": "period_return",
     "rule": "The price column."
    },
    {
     "default": null,
     "name": "entity_column",
     "of": "period_return",
     "rule": "When the request's entity column is not the catalog's."
    },
    {
     "default": null,
     "name": "date_column",
     "of": "period_return",
     "rule": "When the request's time column is not the catalog's."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "The base is the last valid value strictly before the range start, the end the last valid value on or before its end.",
    "Without a history buffer it refuses (PeriodReturnError) instead of using the first value inside the period."
   ],
   "name": "period_return",
   "results": "One row per entity: base_date, base_value, end_date, end_value, return_decimal, return_pct and calculation_status (COMPLETE or why not); leave entities that are not COMPLETE out of rankings.",
   "title": "Return over a named calendar period (YTD, month, quarter, year)",
   "use_when": [
    "A return over a named calendar period, one row per entity, with one boundary convention."
   ],
   "verification": {
    "checked": [
     "the boundary convention and the return formula are the helper's tested code"
    ],
    "level": "BACKEND_HELPER",
    "not_checked": [
     "rankings or averages you compute from its rows"
    ]
   }
  },
  "guide_sha256": "9c3ff9e93115dfb4a91b1e41ca870dff5b0de6c8a448dd657c00ad203eff4b57",
  "guides_version": 1,
  "kind": "HELPER",
  "name": "period_return"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "A column without a catalog resample rule (ResampleRuleMissing): drop it or stay daily."
   ],
   "common_errors": [
    {
     "code": "ResampleRuleMissing",
     "fix": "the column has no catalog rule; keys of the request's grain are not value columns.",
     "seen_in": "P13"
    }
   ],
   "examples": [],
   "g": null,
   "helpers": [
    "resample"
   ],
   "inputs": [
    {
     "name": "frame",
     "of": "resample",
     "rule": "The daily rows (from load or load_range)."
    },
    {
     "name": "request",
     "of": "resample",
     "rule": "The data request id or logical name whose catalog rules apply."
    },
    {
     "default": null,
     "name": "frequency",
     "of": "resample",
     "rule": "The target frequency when the request declares none."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "Each column follows its catalog resample_aggregation (FIRST, LAST, MAX, MIN, SUM).",
    "Compare or rank only periods with period_complete true."
   ],
   "name": "resample",
   "results": "One row per entity and period with period_start, period_end, actual_first_date, actual_last_date, observations and period_complete.",
   "title": "Weekly or monthly rows from daily rows with the catalog's rules",
   "use_when": [
    "A weekly or monthly analysis of a daily request that declared resample."
   ],
   "verification": {
    "checked": [
     "the aggregation of each column is the catalog's rule in the helper's code"
    ],
    "level": "BACKEND_HELPER",
    "not_checked": [
     "what you compute from the periods"
    ]
   }
  },
  "guide_sha256": "40bade75a80b89747fd1441f62387254d490e5bdbe670fc719685919bf598790",
  "guides_version": 1,
  "kind": "HELPER",
  "name": "resample"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "A pandas merge you design yourself: its grain and point-in-time semantics are not checked."
   ],
   "common_errors": [
    {
     "code": "JoinCardinalityError",
     "fix": "preaggregate the many side to the relationship's key grain first.",
     "seen_in": "join"
    }
   ],
   "examples": [],
   "g": null,
   "helpers": [
    "join",
    "preaggregate"
   ],
   "inputs": [
    {
     "name": "relationship_id",
     "of": "join",
     "rule": "The approved relationship."
    },
    {
     "default": null,
     "name": "left",
     "of": "join",
     "rule": "A frame of the left request (default: all of it)."
    },
    {
     "default": null,
     "name": "right",
     "of": "join",
     "rule": "A frame of the right request (default: all of it)."
    },
    {
     "default": null,
     "name": "how",
     "of": "join",
     "rule": "inner or left (default: the relationship's join type)."
    },
    {
     "name": "relationship_id",
     "of": "preaggregate",
     "rule": "The relationship whose many side is reduced to its key grain."
    },
    {
     "default": null,
     "name": "frame",
     "of": "preaggregate",
     "rule": "The many side's rows (default: all of it)."
    },
    {
     "default": null,
     "name": "measures",
     "of": "preaggregate",
     "rule": "The columns to aggregate, each with the catalog's cross-entity rule."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "A column without a catalog cross-entity rule raises AggregationRuleMissing.",
    "A relationship that requires preaggregation accepts only preaggregate's result."
   ],
   "name": "join_and_preaggregate",
   "results": "A frame at the relationship's grain; join_report() gives matched and unmatched rows.",
   "title": "Joining two requests by an approved relationship",
   "use_when": [
    "Combining two requests of the bundle through a relationship the data need approved."
   ],
   "verification": {
    "checked": [
     "the join keys, cardinality and point-in-time semantics of the relationship"
    ],
    "level": "BACKEND_HELPER",
    "not_checked": [
     "the calculation after the join"
    ]
   }
  },
  "guide_sha256": "85469bb5938b70d3d0dab3193633c0243349d602b749aba88c1b5535a2d20040",
  "guides_version": 1,
  "kind": "HELPER",
  "name": "join_and_preaggregate"
 },
 {
  "g": null,
  "guide": {
   "avoid_when": [
    "Reading the input files directly: it counts as not processed."
   ],
   "common_errors": [
    {
     "code": "MaterializationLimitExceeded",
     "fix": "GROUP BY the entity and date columns in sql() first.",
     "seen_in": "G14"
    },
    {
     "code": "SanitiError: 1 is not a data request",
     "fix": "plain range() is Python's; the helper is load_range.",
     "seen_in": "S21"
    }
   ],
   "examples": [
    {
     "code": "for table in carried():\n    print(table['output_id'], table['name'], table['kind'], table['label'])\nearlier = load_output('<output_id>')\nprint(earlier.attrs['label'])",
     "runnable": false,
     "title": "An earlier result as input, with its label"
    },
    {
     "code": "daily = sql('SELECT date, avg(close) AS mean_close FROM prices GROUP BY date ORDER BY date')\nprevious = load_range('prices', 'previous_comparable')\nload('prices')\nload('stock_classification')\nemit_table('daily_mean', daily)",
     "runnable": true,
     "title": "A summary in DuckDB, then one range in pandas"
    }
   ],
   "g": null,
   "helpers": [
    "load",
    "load_range",
    "sql",
    "load_output",
    "carried"
   ],
   "inputs": [
    {
     "name": "request",
     "of": "load",
     "rule": "The data request id or logical name."
    },
    {
     "default": null,
     "name": "columns",
     "of": "load",
     "rule": "Columns to read (default: all)."
    },
    {
     "name": "request",
     "of": "load_range",
     "rule": "The data request id or logical name."
    },
    {
     "name": "range_id",
     "of": "load_range",
     "rule": "One approved range."
    },
    {
     "default": null,
     "name": "columns",
     "of": "load_range",
     "rule": "Columns to read (default: all)."
    },
    {
     "default": false,
     "name": "include_buffers",
     "of": "load_range",
     "rule": "True widens the range to its warm-up and future buffers."
    },
    {
     "name": "query",
     "of": "sql",
     "rule": "DuckDB SQL over one view per logical name."
    },
    {
     "default": null,
     "name": "params",
     "of": "sql",
     "rule": "Query parameters."
    },
    {
     "name": "output_id",
     "of": "load_output",
     "rule": "A released table of this conversation (an analysis table, an event study's tables, a hypothesis plan's aggregates, a multi-angle angle's input), from carried() or the data record."
    },
    {
     "default": null,
     "name": "columns",
     "of": "load_output",
     "rule": "Columns to read (default: all)."
    }
   ],
   "kind": "HELPER",
   "limits": [
    "A request shown as AGGREGATE_FIRST is reduced in sql() before it becomes a pandas frame.",
    "Every approved request and range must be read before complete_analysis.",
    "A research plan's session loads only the carried tables its approved plan names; an analysis session loads any released table of the conversation (24 hours)."
   ],
   "name": "reading_data",
   "results": "pandas frames; the time column holds datetime.date objects and numbers are float64; a carried frame's attrs hold its label and origin.",
   "title": "Reading the bundle: load, load_range and sql",
   "use_when": [
    "Every read of the approved data; sql() first for large requests (summaries in DuckDB)."
   ],
   "verification": {
    "checked": [
     "what was read, per request and range, for coverage",
     "which carried tables were loaded (carried_inputs of the final status, with their labels)"
    ],
    "level": "DATA_COVERAGE_VERIFIED",
    "not_checked": [
     "the SQL or pandas logic"
    ]
   }
  },
  "guide_sha256": "9cdca559f71f0c6bfecb56a66ac5e87cd66bc0c4fe2532d966e0ae0649fcfc49",
  "guides_version": 1,
  "kind": "HELPER",
  "name": "reading_data"
 }
]$guides$::jsonb) AS r(
    name text, guides_version integer, kind text, g text, guide jsonb, guide_sha256 text);

INSERT INTO public."Table_Catalog" (
    table_schema, table_name, category, definition, grain,
    primary_key_columns, source_system, source_tables, source_code_paths,
    update_rule, related_functions, documentation_status,
    readiness_mode, readiness_date_column, observation_date_column,
    data_available_at_column, availability_rule, point_in_time_status,
    historical_metadata_method
) VALUES (
    'public', 'AI_method_guide', 'Reference',
    'Model-facing menu and manual of the analysis paths (G1-G4) and session helpers: when to use and not, inputs, '
    'limits, what the backend checks, results, common errors and tested examples; bound to the code by guides_sha256.',
    'One row per guide and guides version', ARRAY['name', 'guides_version'],
    'apps/market-python-sandbox/app/method_guides.py (byte-identical in market-ai-orc)',
    ARRAY[]::text[], ARRAY['database/migrations/20261002_001_create_ai_method_guide.sql',
                          'apps/market-python-sandbox/app/method_guides.py',
                          'scripts/generate_ai_method_guide_migration.py'],
    'Regenerated by a forward migration whenever the guides in code change; never edited by hand.',
    ARRAY[]::text[], 'VERIFIED', 'NOT_APPLICABLE', NULL, NULL, NULL,
    'Metadata only; enforcement is the sandbox helpers, the harness checks and the orchestrator gates in code.',
    'NOT_APPLICABLE', NULL
);

INSERT INTO public."Column_Catalog" (
    table_schema, table_name, column_name, ordinal_position, data_type,
    is_nullable, default_expression, is_primary_key, definition,
    source_column_or_expression, unit, null_rule, source_code_paths,
    documentation_status
)
SELECT columns.table_schema, columns.table_name, columns.column_name, columns.ordinal_position,
       columns.data_type, columns.is_nullable = 'YES', columns.column_default,
       columns.column_name IN ('name', 'guides_version'),
       CASE columns.column_name
        WHEN 'name' THEN 'Guide name (free_code, event_study, hypothesis_plan, multi_angle or a session helper''s guide).'
        WHEN 'guides_version' THEN 'Version of the method guides content.'
        WHEN 'kind' THEN 'PATH (an analysis path G1-G4) or HELPER (a session helper).'
        WHEN 'g' THEN 'The analysis path G1, G2, G3 or G4; NULL for a helper guide.'
        WHEN 'guide' THEN 'JSON object: when to use and not, inputs with defaults, limits, what the backend checks and does not, results, common errors and examples.'
        WHEN 'guide_sha256' THEN 'Hash of this guide; the conversation data record keeps it to carry the version a model opened.'
        WHEN 'guides_sha256' THEN 'Hash of all guides; market-ai-orc serves them only when it equals the sandbox''s and its own.'
        WHEN 'is_active' THEN 'Whether the guide is offered to the model.'
        WHEN 'created_at' THEN 'Row creation time.'
        WHEN 'updated_at' THEN 'Last update time.'
       END,
       'app/method_guides.py (rows())', NULL,
       CASE WHEN columns.column_name = 'g' THEN 'NULL for a HELPER guide.' ELSE 'NULL is not permitted.' END,
       ARRAY['database/migrations/20261002_001_create_ai_method_guide.sql'], 'VERIFIED'
FROM information_schema.columns AS columns
WHERE columns.table_schema = 'public' AND columns.table_name = 'AI_method_guide';

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
VALUES
    ('get_method_guide', 'DISCOVERY', 'RETRIEVAL', 'Open the manual of one analysis method or helper listed in analysis_methods (the menu at the start of the run and in get_system_capabilities): what it is for and when not to use it, its inputs with their defaults, its limits, what the backend checks and what it does not, its results and how to cite them, common errors from earlier runs and tested examples. Open it before using a method the first time in a conversation; a manual opened earlier in the conversation is already in the context and need not be opened again.',
     '{"additionalProperties":false,"properties":{"name":{"description":"A name from analysis_methods (for example event_study), or a research library method_id while multi-angle research is offered.","type":"string"}},"required":["name"],"type":"object"}'::jsonb,
     '{"description":"The guide (name, version, sha256, the verification level''s meaning and the guide), a research library method''s entry, or REJECTED UNKNOWN_METHOD with the available names.","properties":{"available":{},"code":{},"guide":{},"name":{},"research_library_method":{},"sha256":{},"status":{},"verification_levels":{},"version":{}},"type":"object"}'::jsonb,
     'ORCHESTRATOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 40000, 8, 40000, NULL,
     false, false, false, '{"design": "G2_G3_REACTIVATION_PLAN.md 4b", "feature_flag": "AI_ENABLE_METHOD_GUIDES", "guides_sha256": "d4a032ad33be15326b18a002e9b4044913b00a4b547f65917fc8f82b953cdf58", "handler": "app/tools/method_guides.py (method_guide_spec)", "registry_state": "Registered in market-ai-orc only when AI_method_guide, the sandbox capability method_guides and market-ai-orc''s app/method_guides.py carry the same guides (else method_guides_inactive); is_active=false keeps it out of market-ai-backend tool lists.", "runtime_service": "market-ai-orc"}'::jsonb, 'v1', false);

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."AI_method_guide" WHERE is_active AND guides_sha256 = 'd4a032ad33be15326b18a002e9b4044913b00a4b547f65917fc8f82b953cdf58') <> 8 THEN
        RAISE EXCEPTION 'Expected 8 active method guide rows with the guides hash';
    END IF;
    IF (SELECT count(DISTINCT g) FROM public."AI_method_guide" WHERE kind = 'PATH') <> 4 THEN
        RAISE EXCEPTION 'Expected one guide for each of G1, G2, G3 and G4';
    END IF;
    IF (SELECT count(*) FROM public."Column_Catalog" WHERE table_name = 'AI_method_guide'
          AND definition IS NOT NULL) <> 10
       OR NOT EXISTS (SELECT 1 FROM public."Table_Catalog" WHERE table_name = 'AI_method_guide') THEN
        RAISE EXCEPTION 'AI_method_guide lacks its Table_Catalog / Column_Catalog definitions';
    END IF;
    IF NOT has_table_privilege('market_ai_catalog_reader', 'public."AI_method_guide"', 'SELECT')
       OR has_table_privilege('market_ai_catalog_reader', 'public."AI_method_guide"', 'INSERT,UPDATE,DELETE') THEN
        RAISE EXCEPTION 'market_ai_catalog_reader privileges do not match the read-only contract';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_ai_sql_reader')
       AND has_table_privilege('market_ai_sql_reader', 'public."AI_method_guide"', 'SELECT') THEN
        RAISE EXCEPTION 'The SQL Governor unexpectedly reads the method guides';
    END IF;
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE tool_name = 'get_method_guide' AND version = 'v1'
          AND NOT is_active AND tool_specific_limits->>'runtime_service' = 'market-ai-orc') <> 1 THEN
        RAISE EXCEPTION 'Expected one inactive get_method_guide v1 registration';
    END IF;
END
$verify$;
COMMIT;
