-- Round 2026-10-03 P34 database before the web (ROUND_PLAN_2026-10-03.md): the tool contracts the code now offers.
-- lookup_reference v1: the database's static reference tables (classifications, profiles), read in
-- every reading step including FACT (P34: the FACT step had no database reader and took BBCA's
-- sector from the web). find_web_fact v2: refused once while a reference column holds the asked
-- attribute (one small matcher call over the catalog's reference columns; fail-open); a web fact
-- describes and never enters a calculation.
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_tool_catalog_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN (('find_web_fact', 'v1'))) <> 1 THEN
        RAISE EXCEPTION 'Expected the previous tool versions (''find_web_fact'', ''v1'')';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE (tool_name = 'find_web_fact' AND version = 'v2')) OR EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name IN ('lookup_reference')) THEN
        RAISE EXCEPTION 'The P34 database before the web tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{"design":"ROUND_PLAN_2026-10-03.md (P34 database before the web)","reference_rows":"at most 100 returned, 2000 scanned (else NEEDS_NARROWING), 8 columns, 4 where conditions (EQ or IN of at most 50 values), one text match of 2-60 characters","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here","web_check":"AI_MODEL, reasoning low, strict schema {held, table, column}; the named column must be listed by the Governor, else the web call runs"}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
    ('find_web_fact', 'v1', 'v2', '{"additionalProperties":false,"properties":{"attribute":{"description":"What to find about it, e.g. ''state-owned (BUMN) or private''.","type":"string"},"subject":{"description":"The company, ticker or entity, e.g. ''BBCA''.","type":"string"}},"required":["subject","attribute"],"type":"object"}',
     'One fact that is not in the market data, from the web in about 30 seconds: for example whether a company is state-owned, its controlling shareholder, its listing status or index membership. The backend searches, keeps only values quoted verbatim from their sources and returns CONFIRMED (two independent sites or one official), CONFLICTING (every version), PARTIAL (one site) or NOT_FOUND. Ask one subject and one attribute per call; never use it for prices, volumes or any figure the database holds. A web fact describes: state it in the answer as a web fact; a calculation''s inputs come from the database. An attribute the database''s reference tables hold (sector, industry, company profile) is read with lookup_reference; this tool is refused for it until those tables have been read.')
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
) VALUES
    ('lookup_reference', 'QUERY', 'RETRIEVAL', 'Read the database''s reference tables (static classifications and profiles: a stock''s sector, industry, board, company name or description; a broker''s name or type). Without table: the tables and their columns with descriptions. With table: up to 100 rows, filtered by where (exact stored values; one value or several) and optionally by match (a case-insensitive part of one column''s text, e.g. a group or company name). Use it before find_web_fact for any attribute these tables hold; the web is only for what they do not hold. Rows are current values, not as of past dates; dated data (prices, volumes, flows) needs a data need.',
     '{"additionalProperties":false,"properties":{"columns":{"description":"Columns to return (the entity column is always added); empty when listing.","items":{"type":"string"},"type":"array"},"match":{"anyOf":[{"additionalProperties":false,"properties":{"column":{"description":"The text column to search.","type":"string"},"text":{"description":"A case-insensitive part of its text.","type":"string"}},"required":["column","text"],"type":"object"},{"type":"null"}],"description":"A text search on one column, or null."},"table":{"anyOf":[{"type":"string"},{"type":"null"}],"description":"A reference table, or null to list them."},"where":{"description":"Exact-value conditions, all of them must hold.","items":{"additionalProperties":false,"properties":{"column":{"description":"A column of the table, exactly as listed.","type":"string"},"values":{"description":"Exact stored values; one value, or several for any of them.","items":{"type":"string"},"type":"array"}},"required":["column","values"],"type":"object"},"type":"array"}},"required":["table","columns","where","match"],"type":"object"}'::jsonb,
     '{"description":"without table: the static reference tables (no time column) with their AI-allowed columns and catalog descriptions; with table: at most 100 rows through SQL Governor /v1/catalog/reference-rows (catalog, compile and EXPLAIN gates), matched count, truncated flag; current values, not as of past dates."}'::jsonb,
     'ORCHESTRATOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40000, 200, 40000, NULL,
     false, false, false, '{"design":"ERRORS_AND_SOLUTIONS.md P34; PLAN_2026-10-05.md item 4 (option A)","feature_flag":"AI_ENABLE_REFERENCE_LOOKUP","handler":"app/tools/reference.py","reference_rows":"at most 100 returned, 2000 scanned (else NEEDS_NARROWING), 8 columns, 4 where conditions (EQ or IN of at most 50 values), one text match of 2-60 characters","registry_state":"registered from code (market-ai-orc) under the dev flags, inactive here","web_check":"AI_MODEL, reasoning low, strict schema {held, table, column}; the named column must be listed by the Governor, else the web call runs"}'::jsonb, 'v1', false);

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ((tool_name = 'find_web_fact' AND version = 'v2'))) <> 1
       OR (SELECT count(*) FROM public."Tool_Catalog" WHERE tool_name IN ('lookup_reference') AND version = 'v1' AND NOT is_active) <> 1 THEN
        RAISE EXCEPTION 'The P34 database before the web tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'find_web_fact' AND version = 'v2' AND purpose::text LIKE '%lookup_reference%') THEN
        RAISE EXCEPTION 'The P34 database before the web contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
