"""Write database/migrations/20261003_005_round_b_tool_catalog.sql from market-ai-orc's tool definitions
(ROUND_PLAN_2026-10-03.md, phase B): the tool contracts phase B changed.

- submit_data_need_spec v7 and check_data_feasibility v5: a time range may end "LATEST" (1b / C06).
- check_research_feasibility v4: the same time range contract inside each angle's data requirement.
- run_python v3: event_study takes the approved experiment's outcome unit (P26).

Registered from the code with every switch of the dev environment on (the registry of scripts/generate_ai_tools_doc.py,
one source for both). Each tool's previous registration stays as it was (its migration is applied and frozen);
market-ai-orc's tests/test_data_need_tool.py fails when this migration and the code drift apart.

Usage: apps/market-ai-orc venv python scripts/generate_round_b_tool_migration.py
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sql_text import sql_json, sql_literal  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "database/migrations/20261003_005_round_b_tool_catalog.sql"
VERSIONS = {"submit_data_need_spec": ("v6", "v7"), "check_data_feasibility": ("v4", "v5"),
            "check_research_feasibility": ("v3", "v4"), "run_python": ("v2", "v3")}
# what each new version must carry (checked by the migration itself after the insert)
CONTRACTS = {"submit_data_need_spec": ("input_schema", "LATEST"), "check_data_feasibility": ("input_schema", "LATEST"),
             "check_research_feasibility": ("input_schema", "LATEST"), "run_python": ("purpose", "outcome_unit=None")}


def _tools_doc():
    spec = importlib.util.spec_from_file_location("generate_ai_tools_doc", ROOT / "scripts/generate_ai_tools_doc.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def definitions() -> dict[str, dict]:
    return {name: d for name, d in _tools_doc()._registry().items() if name in VERSIONS}


def schema_text(definition: dict) -> str:
    return sql_json(definition["parameters"], sort_keys=True, separators=(",", ":"))


def render() -> str:
    found = definitions()
    assert set(found) == set(VERSIONS), found.keys()
    limits = {"design": "ROUND_PLAN_2026-10-03.md (phase B)",
              "registry_state": "registered from code (market-ai-orc) under the dev flags, inactive here",
              "time_range_end": "YYYY-MM-DD or LATEST, bound to the reference date by the sandbox (1b)",
              "outcome_unit": "event_study and event_summary use the approved experiment's outcome unit (P26)"}
    rows = ",\n".join(
        f"    ('{name}', '{old}', '{new}', '{schema_text(found[name])}',\n"
        f"     '{sql_literal(found[name]['description'])}')"
        for name, (old, new) in VERSIONS.items())
    previous = ", ".join(f"('{n}', '{old}')" for n, (old, _) in VERSIONS.items())
    registered = " OR ".join(f"(tool_name = '{n}' AND version = '{new}')" for n, (_, new) in VERSIONS.items())
    carried = "\n       OR ".join(
        f"NOT EXISTS (SELECT 1 FROM public.\"Tool_Catalog\" WHERE tool_name = '{n}' AND version = '{VERSIONS[n][1]}'"
        f" AND {column}::text LIKE '%{sql_literal(text)}%')" for n, (column, text) in CONTRACTS.items())
    return f"""-- Round 2026-10-03 phase B (ROUND_PLAN_2026-10-03.md): the tool contracts the code now offers.
-- submit_data_need_spec v7, check_data_feasibility v5, check_research_feasibility v4: a time range may end "LATEST"
-- (1b / C06; the sandbox binds it to the reference date and the bundle reports the actual last date).
-- run_python v3: event_study takes the approved experiment's outcome unit (P26).
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_round_b_tool_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN ({previous})) <> {len(VERSIONS)} THEN
        RAISE EXCEPTION 'Expected the previous tool versions {sql_literal(previous)}';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE {registered}) THEN
        RAISE EXCEPTION 'The phase B tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{sql_json(limits, sort_keys=True, separators=(",", ":"))}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
{rows}
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ({registered})) <> {len(VERSIONS)} THEN
        RAISE EXCEPTION 'The phase B tool versions were not registered';
    END IF;
    IF {carried} THEN
        RAISE EXCEPTION 'The phase B contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
"""


def main() -> None:
    TARGET.write_text(render())
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
