"""Write database/migrations/20261002_002_warehouse_summary_tool_catalog.sql from market-ai-orc's tool definitions
(G18 phase 1, WAREHOUSE_AGGREGATION_PLAN.md): submit_data_need_spec v5 and check_data_feasibility v4 with the
optional per-request `aggregate`, registered from the code under the dev flags (DataNeed, plan feasibility, composite
keys, point in time). market-ai-orc's tests/test_data_need_tool.py fails when the migration and the code drift apart.

Usage: apps/market-ai-orc venv python scripts/generate_warehouse_summary_tool_migration.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "database/migrations/20261002_002_warehouse_summary_tool_catalog.sql"
VERSIONS = {"submit_data_need_spec": ("v4", "v5"), "check_data_feasibility": ("v3", "v4")}
COLUMN_DEFINITION = (
    "Rule for aggregating the column across entities of a finer grain (SUM, MIN, MAX); NULL means the column is not "
    "additive across entities and is never summed. Used by saniti.preaggregate before a relationship join and, since "
    "migration 20261002_002 (G18 phase 1), by a DataNeed request's aggregate: the SQL Governor computes SUM across "
    "entities only for a SUM rule (re-derived from its own catalog contract). Read through the Governor catalog "
    "contract and shown by get_catalog_details.")


def definitions() -> dict[str, dict]:
    sys.path.insert(0, str(ROOT / "apps/market-ai-orc"))
    import httpx

    from app.tools import build_default_registry
    from app.tools.analysis import SandboxClient
    from app.tools.request_data import GovernorClient

    transport = httpx.MockTransport(lambda request: httpx.Response(404))
    registry = build_default_registry(
        object(), cursor_secret=b"x" * 32,
        governor_client=GovernorClient("http://g", "k" * 40, 90, transport=transport),
        sandbox_client=SandboxClient("http://s", "s" * 40, 45, 20, transport=transport), dataneed_enabled=True,
        plan_feasibility=True, composite_keys=True, point_in_time=True)
    return {d["name"]: d for d in registry.definitions() if d["name"] in VERSIONS}


def schema_text(definition: dict) -> str:
    return json.dumps(definition["parameters"], sort_keys=True, separators=(",", ":")).replace("'", "''")


def render() -> str:
    found = definitions()
    assert set(found) == set(VERSIONS), found.keys()
    limits = {"design": "WAREHOUSE_AGGREGATION_PLAN.md (G18 phase 1)", "aggregate": {
        "functions": ["SUM", "MIN", "MAX", "COUNT", "COUNT_DISTINCT"], "direction": "ACROSS_ENTITIES",
        "sum_rule": "AI_column_catalog.cross_entity_aggregation = SUM", "time_column": "kept in group_by",
        "mode": "ANALYSIS"}, "registry_state": "data_need_spec/v2 with time_basis and an optional per-request "
                                              "aggregate; registered from code (market-ai-orc), inactive here"}
    rows = ",\n".join(
        f"    ('{name}', '{old}', '{new}', '{schema_text(found[name])}',\n"
        f"     '{found[name]['description'].replace(chr(39), chr(39) * 2)}')"
        for name, (old, new) in VERSIONS.items())
    preflight_versions = " OR ".join(f"(tool_name = '{n}' AND version = '{new}')" for n, (_, new) in VERSIONS.items())
    return f"""-- G18 phase 1 (WAREHOUSE_AGGREGATION_PLAN.md, user decision 2026-10-02): a DataNeed request may ask the SQL
-- Governor for a summary across entities (aggregate: group_by keeps the time column; SUM only where
-- AI_column_catalog.cross_entity_aggregation is SUM; MIN/MAX of numeric measures; COUNT; COUNT_DISTINCT of identifiers
-- and dimensions). No table or column is added: the direction rules exist since 20260927_005 / 20260928_002.
-- Tool_Catalog: submit_data_need_spec v5 and check_data_feasibility v4, inactive like every market-ai-orc row, input
-- schema and purpose from the code; every other column is copied from the previous version.
-- Column_Catalog / column comment: AI_column_catalog.cross_entity_aggregation now also governs warehouse summaries.
-- GENERATED by scripts/generate_warehouse_summary_tool_migration.py; market-ai-orc tests/test_data_need_tool.py fails
-- on drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN
        (('submit_data_need_spec', 'v4'), ('check_data_feasibility', 'v3'))) <> 2 THEN
        RAISE EXCEPTION 'Expected submit_data_need_spec v4 and check_data_feasibility v3';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE {preflight_versions}) THEN
        RAISE EXCEPTION 'The warehouse summary tool versions are already registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
                   AND table_name = 'AI_column_catalog' AND column_name = 'cross_entity_aggregation') THEN
        RAISE EXCEPTION 'AI_column_catalog.cross_entity_aggregation is required (migration 20260927_005)';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{json.dumps(limits, sort_keys=True, separators=(",", ":"))}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
{rows}
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

COMMENT ON COLUMN public."AI_column_catalog".cross_entity_aggregation IS
    '{COLUMN_DEFINITION.replace(chr(39), chr(39) * 2)}';

UPDATE public."Column_Catalog"
SET definition = '{COLUMN_DEFINITION.replace(chr(39), chr(39) * 2)}',
    source_code_paths = ARRAY['database/migrations/20260927_005_cross_entity_aggregation_and_v2_contracts.sql',
                              'database/migrations/20261002_002_warehouse_summary_tool_catalog.sql',
                              'apps/market-sql-governor/app/catalog_contract.py',
                              'apps/market-sql-governor/app/extract.py',
                              'apps/market-python-sandbox/app/data_need.py',
                              'apps/market-python-sandbox/runtime/saniti_session.py']
WHERE table_schema = 'public' AND table_name = 'AI_column_catalog' AND column_name = 'cross_entity_aggregation';

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ({preflight_versions})
        AND input_schema->'properties'->'data_requests'->'items'->'properties' ? 'aggregate'
        AND input_schema->'properties'->'data_requests'->'items'->'required' ? 'aggregate') <> 2 THEN
        RAISE EXCEPTION 'The warehouse summary tool contracts were not registered';
    END IF;
    IF (SELECT count(*) FROM public."Column_Catalog" WHERE table_name = 'AI_column_catalog'
        AND column_name = 'cross_entity_aggregation' AND definition LIKE '%G18 phase 1%') <> 1 THEN
        RAISE EXCEPTION 'The cross_entity_aggregation definition was not updated';
    END IF;
    IF (SELECT count(*) FROM public."AI_column_catalog" WHERE cross_entity_aggregation = 'SUM') <> 26 THEN
        RAISE EXCEPTION 'The cross-entity SUM rules changed unexpectedly';
    END IF;
END
$verify$;

COMMIT;
"""


if __name__ == "__main__":
    TARGET.write_text(render())
    print(f"wrote {TARGET.relative_to(ROOT)}")
