"""Write database/migrations/20260930_001_create_ai_research_library.sql from the research library in code
(apps/market-python-sandbox/app/research_library.py, byte-identical in market-ai-orc). The sandbox test
tests/test_research_library.py fails when the migration and the library drift apart.

Usage: python scripts/generate_ai_research_library_migration.py
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sql_text import sql_json, sql_literal  # noqa: E402,F401

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "database/migrations/20260930_001_create_ai_research_library.sql"
COLUMNS = [
    ("method_id", "text", "Registered method id (research_plan/v2 method_id)."),
    ("engine_version", "integer", "Version of the statistical engines the row describes."),
    ("library_version", "integer", "Version of the research library content."),
    ("method_family", "text", "One of the five method families; an agreement between angles needs two families."),
    ("question_shape", "text", "The question the method answers, in general form."),
    ("input_roles", "jsonb", "JSON array of input roles (role, type, required, meaning); logical roles, not column names."),
    ("required_parameters", "jsonb", "JSON array of the parameters an angle of this method must set, with their rules."),
    ("optional_parameters", "jsonb", "JSON array of the parameters an angle may set, with their rules."),
    ("data_requirements", "jsonb", "JSON object: entity column, label constancy, outcome kind, minimum entities per date and notes; the feasibility check enforces them."),
    ("common_requirements", "jsonb", "JSON array of the requirements every method shares (one row per entity and date, declarations, forward returns)."),
    ("sample_unit", "text", "Unit of the effective sample: DATES, ENTITIES or DATES_AUTOCORRELATION_ADJUSTED."),
    ("secondary_checks", "jsonb", "JSON array of checks that must pass for SUPPORTED (for example monotonicity)."),
    ("decision_rules_ref", "text", "Where the status rules are defined; enforcement is research_engines.decide in code."),
    ("interpretation", "text", "What the method's estimate means."),
    ("misuse_warning", "text", "How the result is commonly misread."),
    ("example_question", "text", "An illustrative question the method answers."),
    ("library_sha256", "text", "Hash of the whole library; market-ai-orc enables multi-angle research only when it equals the sandbox's and its own."),
    ("is_active", "boolean", "Whether the method is offered to the model."),
    ("created_at", "timestamp with time zone", "Row creation time."),
    ("updated_at", "timestamp with time zone", "Last update time."),
]


def load_library():
    path = ROOT / "apps/market-python-sandbox/app/research_library.py"
    spec = importlib.util.spec_from_file_location("research_library", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render() -> str:
    library = load_library()
    rows = library.rows()
    payload = json.dumps(rows, ensure_ascii=False, sort_keys=True, indent=1)
    assert "$library$" not in payload
    sha = library.LIBRARY_SHA256
    definitions = "\n".join(f"        WHEN '{name}' THEN '{sql_literal(text)}'"
                            for name, _, text in COLUMNS)
    return f"""-- Multi-Angle Research: the research library (C07; MULTI_ANGLE_FIX_PLAN.md item 2, user decision 2026-09-29).
-- public."AI_research_library" is the model-facing description of the eight methods the sandbox engines compute;
-- market-ai-orc serves it (get_research_library) instead of listing methods in its system prompt. It describes, it
-- does not compute: a new row does not create a method. AI_research_catalog is not touched.
-- GENERATED by scripts/generate_ai_research_library_migration.py from apps/market-python-sandbox/app/research_library.py
-- (library_sha256 {sha}); the sandbox test tests/test_research_library.py fails on drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF to_regclass('public."AI_research_library"') IS NOT NULL THEN
        RAISE EXCEPTION 'AI_research_library already exists';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_ai_catalog_reader') THEN
        RAISE EXCEPTION 'market_ai_catalog_reader role is required';
    END IF;
END
$preflight$;

CREATE TABLE public."AI_research_library" (
    method_id text NOT NULL,
    engine_version integer NOT NULL,
    library_version integer NOT NULL,
    method_family text NOT NULL,
    question_shape text NOT NULL,
    input_roles jsonb NOT NULL,
    required_parameters jsonb NOT NULL,
    optional_parameters jsonb NOT NULL,
    data_requirements jsonb NOT NULL,
    common_requirements jsonb NOT NULL,
    sample_unit text NOT NULL,
    secondary_checks jsonb NOT NULL,
    decision_rules_ref text NOT NULL,
    interpretation text NOT NULL,
    misuse_warning text NOT NULL,
    example_question text NOT NULL,
    library_sha256 text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AI_research_library_pkey" PRIMARY KEY (method_id, engine_version),
    CONSTRAINT ai_research_library_family CHECK (method_family IN ('CONDITIONAL_OUTCOME', 'PERSISTENCE',
        'GROUP_COMPARISON', 'QUANTILE_RANKING', 'TEMPORAL_DEPENDENCY')),
    CONSTRAINT ai_research_library_sample_unit CHECK (sample_unit IN ('DATES', 'ENTITIES',
        'DATES_AUTOCORRELATION_ADJUSTED')),
    CONSTRAINT ai_research_library_sha CHECK (library_sha256 ~ '^[0-9a-f]{{64}}$'),
    CONSTRAINT ai_research_library_json CHECK (
        jsonb_typeof(input_roles) = 'array' AND jsonb_typeof(required_parameters) = 'array'
        AND jsonb_typeof(optional_parameters) = 'array' AND jsonb_typeof(data_requirements) = 'object'
        AND jsonb_typeof(common_requirements) = 'array' AND jsonb_typeof(secondary_checks) = 'array'),
    CONSTRAINT ai_research_library_method_id CHECK (method_id ~ '^[a-z][a-z0-9_]{{0,62}}$')
);
COMMENT ON TABLE public."AI_research_library" IS
    'Model-facing description of the Multi-Angle Research methods the sandbox engines compute; generated from code, '
    'hash-bound (library_sha256). Enforcement stays in code.';

-- market-ai-orc's catalog login inherits this role; the SQL Governor role gets no grant.
GRANT SELECT ON public."AI_research_library" TO market_ai_catalog_reader;
REVOKE ALL ON public."AI_research_library" FROM PUBLIC;

INSERT INTO public."AI_research_library" (
    method_id, engine_version, library_version, method_family, question_shape, input_roles, required_parameters,
    optional_parameters, data_requirements, common_requirements, sample_unit, secondary_checks, decision_rules_ref,
    interpretation, misuse_warning, example_question, library_sha256
)
SELECT r.method_id, r.engine_version, r.library_version, r.method_family, r.question_shape, r.input_roles,
       r.required_parameters, r.optional_parameters, r.data_requirements, r.common_requirements, r.sample_unit,
       r.secondary_checks, r.decision_rules_ref, r.interpretation, r.misuse_warning, r.example_question,
       '{sha}'
FROM jsonb_to_recordset($library${payload}$library$::jsonb) AS r(
    method_id text, engine_version integer, library_version integer, method_family text, question_shape text,
    input_roles jsonb, required_parameters jsonb, optional_parameters jsonb, data_requirements jsonb,
    common_requirements jsonb, sample_unit text, secondary_checks jsonb, decision_rules_ref text,
    interpretation text, misuse_warning text, example_question text);

INSERT INTO public."Table_Catalog" (
    table_schema, table_name, category, definition, grain,
    primary_key_columns, source_system, source_tables, source_code_paths,
    update_rule, related_functions, documentation_status,
    readiness_mode, readiness_date_column, observation_date_column,
    data_available_at_column, availability_rule, point_in_time_status,
    historical_metadata_method
) VALUES (
    'public', 'AI_research_library', 'Reference',
    'Model-facing description of the eight Multi-Angle Research methods (roles, parameters, data requirements, '
    'interpretation, misuse warning), generated from the sandbox research library and bound to it by library_sha256.',
    'One row per research method and engine version', ARRAY['method_id', 'engine_version'],
    'apps/market-python-sandbox/app/research_library.py (byte-identical in market-ai-orc)',
    ARRAY[]::text[], ARRAY['database/migrations/20260930_001_create_ai_research_library.sql',
                          'apps/market-python-sandbox/app/research_library.py',
                          'scripts/generate_ai_research_library_migration.py'],
    'Regenerated by a forward migration whenever the library in code changes; never edited by hand.',
    ARRAY[]::text[], 'VERIFIED', 'NOT_APPLICABLE', NULL, NULL, NULL,
    'Metadata only; enforcement is the engines and the feasibility check in code.',
    'NOT_APPLICABLE', NULL
);

INSERT INTO public."Column_Catalog" (
    table_schema, table_name, column_name, ordinal_position, data_type,
    is_nullable, default_expression, is_primary_key, definition,
    source_column_or_expression, unit, null_rule, source_code_paths,
    documentation_status
)
SELECT columns.table_schema, columns.table_name, columns.column_name, columns.ordinal_position,
       columns.data_type, false, columns.column_default, columns.column_name IN ('method_id', 'engine_version'),
       CASE columns.column_name
{definitions}
       END,
       'app/research_library.py (rows())', NULL, 'NULL is not permitted.',
       ARRAY['database/migrations/20260930_001_create_ai_research_library.sql'], 'VERIFIED'
FROM information_schema.columns AS columns
WHERE columns.table_schema = 'public' AND columns.table_name = 'AI_research_library';

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."AI_research_library" WHERE is_active AND library_sha256 = '{sha}') <> {len(rows)}
       OR (SELECT count(DISTINCT method_family) FROM public."AI_research_library") <> 5 THEN
        RAISE EXCEPTION 'Expected {len(rows)} active research library rows with the library hash and five families';
    END IF;
    IF (SELECT count(*) FROM public."Column_Catalog" WHERE table_name = 'AI_research_library'
          AND definition IS NOT NULL) <> {len(COLUMNS)}
       OR NOT EXISTS (SELECT 1 FROM public."Table_Catalog" WHERE table_name = 'AI_research_library') THEN
        RAISE EXCEPTION 'AI_research_library lacks its Table_Catalog / Column_Catalog definitions';
    END IF;
    IF NOT has_table_privilege('market_ai_catalog_reader', 'public."AI_research_library"', 'SELECT')
       OR has_table_privilege('market_ai_catalog_reader', 'public."AI_research_library"', 'INSERT,UPDATE,DELETE') THEN
        RAISE EXCEPTION 'market_ai_catalog_reader privileges do not match the read-only contract';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'market_ai_sql_reader')
       AND has_table_privilege('market_ai_sql_reader', 'public."AI_research_library"', 'SELECT') THEN
        RAISE EXCEPTION 'The SQL Governor unexpectedly reads the research library';
    END IF;
END
$verify$;
COMMIT;
"""


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
