"""Write database/migrations/20261003_003_high_alert_tool_catalog.sql from market-ai-orc's tool definitions
(HIGH_ALERT_IMPLEMENTATION_PLAN.md, steps 3-5): submit_data_need_spec v6 (research findings fields with the numeric
success_rule, M28) and run_python v2 (output definitions, H1; the event flow table, S27). Registered from the code
under the dev flags (DataNeed, plan feasibility, composite keys, point in time, research findings, standard period
return, event study). run_python v1 was registered in 20260926_001 and had drifted from the code (C08); v2 is the
code's description. market-ai-orc's tests/test_data_need_tool.py fails when the migration and the code drift apart.

Usage: apps/market-ai-orc venv python scripts/generate_high_alert_tool_migration.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sql_text import sql_json, sql_literal  # noqa: E402,F401

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "database/migrations/20261003_003_high_alert_tool_catalog.sql"
VERSIONS = {"submit_data_need_spec": ("v5", "v6"), "run_python": ("v1", "v2")}


def definitions() -> dict[str, dict]:
    sys.path.insert(0, str(ROOT / "apps/market-ai-orc"))
    import httpx

    from app.tools import build_default_registry
    from app.tools.analysis import SandboxClient
    from app.tools.request_data import GovernorClient

    transport = httpx.MockTransport(lambda request: httpx.Response(404))
    registry = build_default_registry(
        object(), cursor_secret=b"x" * 32,
        governor_client=GovernorClient("http://g", "k" * 40, 90, transport=transport),
        sandbox_client=SandboxClient("http://s", "s" * 40, 45, 20, transport=transport), dataneed_enabled=True,
        plan_feasibility=True, composite_keys=True, point_in_time=True, research_findings=True,
        standard_period_return=True, event_study=True)
    return {d["name"]: d for d in registry.definitions() if d["name"] in VERSIONS}


def schema_text(definition: dict) -> str:
    return sql_json(definition["parameters"], sort_keys=True, separators=(",", ":"))


def render() -> str:
    found = definitions()
    assert set(found) == set(VERSIONS), found.keys()
    limits = {"design": "HIGH_ALERT_IMPLEMENTATION_PLAN.md (steps 3-5)",
              "registry_state": "registered from code (market-ai-orc) under the dev flags, inactive here",
              "output_definition": "every released table or JSON states its definition (H1)",
              "success_rule": "the approved plan's numeric success threshold, applied by event_summary (M28)"}
    rows = ",\n".join(
        f"    ('{name}', '{old}', '{new}', '{schema_text(found[name])}',\n"
        f"     '{sql_literal(found[name]['description'])}')"
        for name, (old, new) in VERSIONS.items())
    previous = ", ".join(f"('{n}', '{old}')" for n, (old, _) in VERSIONS.items())
    registered = " OR ".join(f"(tool_name = '{n}' AND version = '{new}')" for n, (_, new) in VERSIONS.items())
    return f"""-- HIGH ALERT (HIGH_ALERT_IMPLEMENTATION_PLAN.md, user decisions 2026-10-02): the tool contracts the code now offers.
-- submit_data_need_spec v6: research_governance carries the research findings values, including success_rule, the
-- approved plan's numeric success threshold that event_summary applies (M28).
-- run_python v2: emit_table/emit_json take definition (H1, every released result states how it was made), and the
-- event study releases its flow table (S27); v1 had drifted from the code (C08).
-- Inactive like every market-ai-orc row; input schema and purpose from the code, every other column copied from the
-- previous version.
-- GENERATED by scripts/generate_high_alert_tool_migration.py; market-ai-orc tests/test_data_need_tool.py fails on
-- drift. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '1min';

DO $preflight$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE (tool_name, version) IN ({previous})) <> {len(VERSIONS)} THEN
        RAISE EXCEPTION 'Expected the previous tool versions {sql_literal(previous)}';
    END IF;
    IF EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE {registered}) THEN
        RAISE EXCEPTION 'The HIGH ALERT tool versions are already registered';
    END IF;
END
$preflight$;

INSERT INTO public."Tool_Catalog" (
    tool_name, tool_family, tool_type, purpose, input_schema, output_schema,
    execution_type, handler_name, default_output_rows, max_output_rows,
    max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
    timeout_seconds, max_output_bytes, max_llm_result_rows,
    max_llm_result_bytes, max_llm_result_tokens,
    requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
    tool_specific_limits, version, is_active
)
SELECT tool_name, tool_family, tool_type, next.purpose, next.input_schema::jsonb, output_schema,
       execution_type, handler_name, default_output_rows, max_output_rows,
       max_input_rows, max_tickers, max_date_range_days, max_estimated_rows,
       timeout_seconds, max_output_bytes, max_llm_result_rows,
       max_llm_result_bytes, max_llm_result_tokens,
       requires_analytics_worker, requires_feature_catalog, requires_data_readiness,
       tool_specific_limits || '{sql_json(limits, sort_keys=True, separators=(",", ":"))}'::jsonb, next.version, false
FROM public."Tool_Catalog" AS previous
JOIN (VALUES
{rows}
) AS next(name, from_version, version, input_schema, purpose)
  ON previous.tool_name = next.name AND previous.version = next.from_version;

DO $verify$
BEGIN
    IF (SELECT count(*) FROM public."Tool_Catalog" WHERE NOT is_active AND ({registered})) <> {len(VERSIONS)} THEN
        RAISE EXCEPTION 'The HIGH ALERT tool versions were not registered';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'submit_data_need_spec' AND version = 'v6'
                   AND input_schema::text LIKE '%success_rule%')
       OR NOT EXISTS (SELECT 1 FROM public."Tool_Catalog" WHERE tool_name = 'run_python' AND version = 'v2'
                      AND purpose LIKE '%definition=%' AND purpose LIKE '%_flow%') THEN
        RAISE EXCEPTION 'The HIGH ALERT contracts are not in the registered rows';
    END IF;
END
$verify$;

COMMIT;
"""


if __name__ == "__main__":
    TARGET.write_text(render())
    print(f"wrote {TARGET.relative_to(ROOT)}")
